export interface CocktailCollection {
  slug: string
  title: string
  desc: string
  emoji: string
  img: string
  slugs: string[]
}

export const COCKTAIL_COLLECTIONS: CocktailCollection[] = [
  {
    slug: 'clasice',
    title: 'Cocktailuri Clasice',
    desc: 'Rețete clasice desăvârșite',
    emoji: '🍸',
    img: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&q=80',
    slugs: [
      'old-fashioned', 'classic-negroni', 'negroni', 'dry-martini', 'martini', 'manhattan',
      'daiquiri', 'whiskey-sour', 'sidecar', 'sazerac', 'gimlet', 'aviation',
      'boulevardier', 'last-word', 'corpse-reviver-no-2', 'clover-club', 'hanky-panky',
      'martinez', 'vieux-carre', 'pisco-sour', 'vesper', 'hemingway-special',
      'mint-julep', 'caipirinha', 'margarita', 'cosmopolitan', 'long-island-iced-tea',
      'singapore-sling', 'cuba-libre', 'tom-collins', 'john-collins', 'gin-fizz',
      'white-lady', 'alexander', 'brandy-alexander', 'americano', 'angel-face',
      'between-the-sheets', 'brandy-crusta', 'casino', 'mary-pickford', 'monkey-gland',
      'paradise', 'planters-punch', 'porto-flip', 'ramos-gin-fizz', 'remember-the-maine',
      'rob-roy', 'rusty-nail', 'stinger', 'tuxedo', 'penicillin', 'paper-plane',
      'gold-rush', 'bees-knees', 'naked-and-famous', 'trinidad-sour', 'espresso-martini',
      'negroni-sbagliato',
    ],
  },
  {
    slug: 'racoritoare-de-vara',
    title: 'Răcoritoare de Vară',
    desc: 'Ușoare, răcoritoare și fructate',
    emoji: '☀️',
    img: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&q=80',
    slugs: [
      'mojito', 'paloma', 'aperol-spritz', 'gin-tonic', 'pina-colada',
      'moscow-mule', 'sea-breeze', 'tequila-sunrise', 'lemon-drop', 'sex-on-the-beach',
      'hugo-spritz', 'frozen-margarita', 'frozen-daiquiri', 'frozen-strawberry-daiquiri',
      'strawberry-margarita', 'watermelon-martini', 'mango-mojito', 'coconut-mojito',
      'caipirinha', 'pimms-cup', 'sangria', 'white-sangria', 'sweet-sangria',
      'limoncello-spritz', 'rhubarb-gin-spritz', 'rose-spritz', 'spritz-veneziano',
      'cucumber-collins', 'tom-collins', 'rum-punch', 'cranberry-mule', 'kentucky-mule',
      'gin-gin-mule', 'limoncello-mule', 'mezcal-mule', 'mexican-mule',
      'watermelon-sugar-high', 'watermelon-mint-cooler', 'strawberry-basil-gin-smash',
      'peach-bourbon-smash', 'gin-cooler', 'rum-cooler', 'wine-cooler',
      'raspberry-cooler', 'cucumber-cooler', 'fruit-cooler',
    ],
  },
  {
    slug: 'incalzitoare-de-iarna',
    title: 'Încălzitoare de Iarnă',
    desc: 'Condimentate, calde și reconfortante',
    emoji: '🔥',
    img: 'https://images.unsplash.com/photo-1578897367052-e0e6b5b0b2b0?w=600&q=80',
    slugs: [
      'irish-coffee', 'hot-toddy', 'mulled-wine', 'gluhwein', 'glogg',
      'hot-buttered-rum-classic', 'buttered-rum', 'eggnog-cocktail', 'eggnog-flip',
      'tom-and-jerry', 'chai-old-fashioned', 'mulled-cider', 'mexican-hot-chocolate-cocktail',
      'caribbean-coffee', 'jamaican-coffee', 'karsk', 'hot-chocolate-to-die-for',
      'masala-chai-cocktail', 'fireball-cider', 'hot-creamy-bush', 'kioki-coffee',
      'ginger-lemon-shrub', 'spiced-apple-cider-mocktail', 'chai-spiced-latte-mocktail',
      'winter-paloma', 'winter-rita', 'rum-toddy', 'gin-toddy', 'turkish-coffee-martini',
      'sherry-eggnog', 'grogue-cocktail-cape-verde', 'nuked-hot-chocolate',
      'orange-scented-hot-chocolate', 'masala-chai', 'navy-grog',
    ],
  },
  {
    slug: 'bauturi-usoare',
    title: 'Băuturi Ușoare',
    desc: 'Savoare fără exces',
    emoji: '🌱',
    img: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?w=600&q=80',
    slugs: [
      'aperol-spritz', 'hugo-spritz', 'spritz', 'shirley-temple', 'virgin-mojito',
      'arnold-palmer', 'virgin-pina-colada', 'virgin-pina-colada-frozen', 'kir', 'kir-royale',
      'bellini', 'americano', 'campari-and-soda', 'garibaldi', 'spritzer',
      'virgin-mary', 'virgin-espresso-martini', 'nojito', 'bora-bora',
      'elderflower-collins-mocktail', 'grapefruit-paloma-mocktail', 'peach-bellini-mocktail',
      'rhubarb-fizz-mocktail', 'berry-smash-mocktail', 'blueberry-basil-smash-mocktail',
      'tropical-sunrise-mocktail', 'smoky-pineapple-mocktail', 'mango-lassi-mocktail',
      'ginger-beer-mocktail', 'horchata-mocktail', 'kefir-smoothie-mocktail',
      'ube-latte-mocktail', 'seedlip-garden-and-tonic', 'crodino-spritz',
      'elderflower-and-cucumber-cooler', 'italian-soda', 'roy-rogers',
      'chai-spiced-latte-mocktail', 'spiced-apple-cider-mocktail',
    ],
  },
  {
    slug: 'cocktailuri-de-brunch',
    title: 'Cocktailuri de Brunch',
    desc: 'Mimosa, Bloody Mary și altele',
    emoji: '🥂',
    img: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80',
    slugs: [
      'mimosa', 'bloody-mary', 'bellini', 'french-75', 'french-76', 'bucks-fizz',
      'kir', 'kir-royale', 'champagne-cocktail', 'rossini', 'puccini', 'tintoretto',
      'arnold-palmer', 'screwdriver', 'harvey-wallbanger', 'ramos-gin-fizz', 'ramos-fizz',
      'greyhound', 'salty-dog', 'michelada', 'paloma', 'tequila-sunrise',
      'garibaldi', 'pimms-cup', 'seelbach-cocktail', 'death-in-the-afternoon',
      'chambord-royale', 'apple-cider-mimosa', 'laksa-bloody-mary', 'radler',
      'peach-bellini-mocktail', 'aperol-spritz', 'rum-screwdriver',
    ],
  },
  {
    slug: 'tiki-tropicale',
    title: 'Tiki & Tropicale',
    desc: 'Evadare cu rom intens',
    emoji: '🏝️',
    img: 'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&q=80',
    slugs: [
      'mai-tai', 'zombie', 'pina-colada', 'hurricane-original', 'hurricane-pat-obrien',
      'jungle-bird', 'navy-grog', 'painkiller', 'rum-runner', 'scorpion-bowl',
      'three-dots-and-a-dash', 'test-pilot', 'jet-pilot', 'fog-cutter', 'blue-hawaii',
      'bahama-mama', 'dark-and-stormy', 'dark-n-stormy', 'dark-n-stormy-bermuda',
      'ancient-mariner', 'barracuda', 'bermuda-rum-swizzle', 'chartreuse-swizzle',
      'cobras-fang', 'doctor-funk', 'missionarys-downfall', 'nuclear-daiquiri',
      'port-au-prince', 'port-royal', 'queens-park-swizzle', 'rum-punch',
      'rum-punch-caribbean', 'rum-punch-classic', 'tiki-ti-rays-mistake', 'tiki-ti-special',
      'tradewinds', 'ube-colada', 'yellow-bird', 'corn-n-oil', 'suffering-bastard-tiki',
      'mango-rum-punch', 'virgin-pina-colada', 'virgin-pina-colada-frozen',
      'oleo-saccharum-punch', 'bora-bora', 'gin-swizzle', 'rum-swizzle',
    ],
  },
]
