/**
 * Multilingual Ingredient Alias Dictionary
 *
 * Maps foreign-language ingredient names → English canonical name.
 * Used in search to expand queries so "ardei" finds recipes with "pepper".
 *
 * ─── Sustainable Architecture Note ──────────────────────────────────────────
 * This file is the MVP bridge until the Supabase ingredient table is live.
 *
 * Future DB schema (canonical ingredients — self-managing):
 *
 *   CREATE TABLE ingredients (
 *     id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 *     canonical          text NOT NULL UNIQUE,     -- English master: "pepper"
 *     name_translations  jsonb DEFAULT '{}',        -- {ro:"ardei", fr:"poivron", ...}
 *     aliases            text[] DEFAULT '{}',       -- ["bell pepper","capsicum"]
 *     category           text,                      -- "vegetable","spice","protein","dairy"
 *     created_at         timestamptz DEFAULT now()
 *   );
 *
 *   -- GIN index across all language variants for fast full-text search:
 *   CREATE INDEX ingredients_search_idx ON ingredients
 *     USING gin(to_tsvector('simple',
 *       canonical || ' ' || array_to_string(aliases, ' ') || ' ' ||
 *       (SELECT string_agg(v::text, ' ') FROM jsonb_each_text(name_translations))
 *     ));
 *
 * How it becomes self-managing:
 *   - When a Romanian user adds a recipe with ingredient "ardei", the submission UI
 *     suggests canonical matches. If they confirm "ardei = pepper", that translation
 *     is written once to ingredients.name_translations['ro'] = 'ardei'.
 *   - Search queries against that table — no dictionary file to maintain.
 *   - Migration: seed the ingredients table from this file with a one-time script.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Languages covered (24):
 *   RO Romanian · FR French · ES Spanish · IT Italian · DE German
 *   PT Portuguese · NL Dutch · PL Polish · CS Czech · SK Slovak
 *   HU Hungarian · SV Swedish · DA Danish · NO Norwegian · FI Finnish
 *   EL Greek (romanised) · HR Croatian · BG Bulgarian (romanised)
 *   SR Serbian (romanised) · SL Slovenian · LT Lithuanian · LV Latvian
 *   ET Estonian · TR Turkish
 *
 * Rules:
 *   - All keys lowercase, no diacritics where there's a common ASCII spelling
 *     (but keep native spelling for accuracy, e.g. "möhre" not "mohre")
 *   - Each key appears ONCE — cross-language homographs go in the shared section
 *   - Value is always the English canonical name
 */

// ─── Helper: build the flat alias map ────────────────────────────────────────
// We use a builder so we can detect duplicate keys at runtime in dev.

function buildAliases(entries: [string, string][]): Record<string, string> {
  const map: Record<string, string> = {};
  for (const [alias, canonical] of entries) {
    if (process.env.NODE_ENV === 'development' && alias in map && map[alias] !== canonical) {
      console.warn(`[ingredient-aliases] Conflicting alias "${alias}": "${map[alias]}" vs "${canonical}"`);
    }
    map[alias] = canonical;
  }
  return map;
}

// ─────────────────────────────────────────────────────────────────────────────

export const INGREDIENT_ALIASES: Record<string, string> = buildAliases([

  // ═══════════════════════════════════════════════════════════════════════════
  // ROMANIAN (ro)
  // ═══════════════════════════════════════════════════════════════════════════
  ['ardei', 'pepper'],
  ['ardei gras', 'bell pepper'],
  ['ardei iute', 'chili pepper'],
  ['ardei rosu', 'red pepper'],
  ['ardei verde', 'green pepper'],
  ['branza', 'cheese'],
  ['branza de vaci', 'cottage cheese'],
  ['branza feta', 'feta cheese'],
  ['cartofi', 'potato'],
  ['cartofi dulci', 'sweet potato'],
  ['castravete', 'cucumber'],
  ['castraveti', 'cucumber'],
  ['ceapa', 'onion'],
  ['ceapa rosie', 'red onion'],
  ['ceapa verde', 'scallion'],
  ['ciuperci', 'mushroom'],
  ['conopida', 'cauliflower'],
  ['dovleac', 'pumpkin'],
  ['dovlecel', 'zucchini'],
  ['fasole', 'beans'],
  ['fasole verde', 'green beans'],
  ['faina', 'flour'],
  ['lapte', 'milk'],
  ['lamaie', 'lemon'],
  ['linte', 'lentils'],
  ['marar', 'dill'],
  ['miere', 'honey'],
  ['morcov', 'carrot'],
  ['morcovi', 'carrot'],
  ['ou', 'egg'],
  ['oua', 'eggs'],
  ['orez', 'rice'],
  ['patrunjel', 'parsley'],
  ['piper', 'black pepper'],
  ['porumb', 'corn'],
  ['rosie', 'tomato'],
  ['rosii', 'tomato'],
  ['sfecla', 'beet'],
  ['smantana', 'sour cream'],
  ['spanac', 'spinach'],
  ['sun', 'ham'],
  ['sunca', 'ham'],
  ['telina', 'celery'],
  ['ulei', 'oil'],
  ['ulei de masline', 'olive oil'],
  ['usturoi', 'garlic'],
  ['varza', 'cabbage'],
  ['varza rosie', 'red cabbage'],
  ['vinete', 'eggplant'],
  ['zahar', 'sugar'],
  ['zmeura', 'raspberry'],
  ['capsuni', 'strawberry'],
  ['mere', 'apple'],
  ['pere', 'pear'],
  ['piersici', 'peach'],
  ['carne de vita', 'beef'],
  ['carne de porc', 'pork'],
  ['carne de pui', 'chicken'],
  ['pui', 'chicken'],
  ['vita', 'beef'],
  ['ton', 'tuna'],
  ['somon', 'salmon'],
  ['creveti', 'shrimp'],
  ['unt', 'butter'],
  ['smantana dulce', 'cream'],
  ['iaurt', 'yogurt'],
  ['otet', 'vinegar'],
  ['sare', 'salt'],
  ['zahar brun', 'brown sugar'],
  ['scortisoara', 'cinnamon'],
  ['busuioc', 'basil'],
  ['oregano', 'oregano'],
  ['cimbru', 'thyme'],
  ['chimen', 'cumin'],
  ['boia', 'paprika'],
  ['boia de ardei', 'paprika'],
  ['boia dulce', 'sweet paprika'],
  ['boia iute', 'hot paprika'],
  ['piper negru', 'black pepper'],
  ['piper alb', 'white pepper'],
  ['ulei vegetal', 'vegetable oil'],
  ['ulei de cocos', 'coconut oil'],
  ['ulei de palmier', 'palm oil'],
  ['faina universala', 'all-purpose flour'],
  ['suc de lamaie', 'lemon juice'],
  ['lapte de cocos', 'coconut milk'],
  ['lapte integral', 'whole milk'],
  ['praf de copt', 'baking powder'],
  ['bicarbonat de sodiu', 'baking soda'],
  ['extract de vanilie', 'vanilla extract'],
  ['sos de soia', 'soy sauce'],
  ['pasta de tomate', 'tomato paste'],
  ['pasta de rosii', 'tomato paste'],
  ['coriandru', 'coriander'],
  ['ghimbir', 'ginger'],
  ['nucsoara', 'nutmeg'],
  ['dafin', 'bay leaf'],
  ['frunze de dafin', 'bay leaves'],
  ['foi de dafin', 'bay leaves'],
  ['amidon de porumb', 'cornstarch'],
  ['pesmet', 'breadcrumbs'],
  ['smantana groasa', 'heavy cream'],
  ['smantana dulce', 'cream'],
  ['orez cu bob lung', 'long grain rice'],
  ['carne de vita tocata', 'ground beef'],
  ['miel', 'lamb'],
  ['bulion de vita', 'beef broth'],
  ['bulion de carne', 'beef broth'],
  ['bulion de legume', 'vegetable broth'],
  ['bulion de pui', 'chicken broth'],
  ['apa', 'water'],
  ['cepe', 'onion'],
  ['patlagini', 'plantain'],
  ['bacon', 'bacon'],
  ['migdale', 'almonds'],
  ['fistic', 'pistachios'],
  ['seminte de mac', 'poppy seeds'],
  ['seminte de susan', 'sesame seeds'],
  ['seminte de in', 'flax seeds'],
  ['cardamom', 'cardamom'],
  ['turmeric', 'turmeric'],
  ['curcuma', 'turmeric'],
  ['drojdie', 'yeast'],
  ['drojdie uscata', 'dry yeast'],
  ['ghee', 'ghee'],
  ['patrunjel proaspat', 'fresh parsley'],
  ['apa de trandafiri', 'rose water'],

  // ── Romanian: meat cuts (bucăți de carne) ───────────────────────────────
  // Pork (porc)
  ['umar de porc', 'pork shoulder'],        // shoulder pork / spată
  ['spata de porc', 'pork shoulder'],       // shoulder blade cut
  ['spată de porc', 'pork shoulder'],
  ['muschi de porc', 'pork tenderloin'],    // tenderloin
  ['mușchi de porc', 'pork tenderloin'],
  ['cotlet de porc', 'pork chop'],
  ['fleica de porc', 'pork belly'],         // belly / streaky
  ['fleică de porc', 'pork belly'],
  ['burtă de porc', 'pork belly'],
  ['burta de porc', 'pork belly'],
  ['costita de porc', 'pork ribs'],         // ribs
  ['costiță de porc', 'pork ribs'],
  ['carne tocata de porc', 'ground pork'],  // minced pork
  ['carne tocată de porc', 'ground pork'],
  ['porc tocat', 'ground pork'],
  ['carnati de porc', 'sausage'],           // pork sausages
  ['cârnați de porc', 'sausage'],
  ['carnati', 'sausage'],
  ['cârnați', 'sausage'],
  ['carnat', 'sausage'],
  ['crenvursti', 'hot dog'],
  ['crenvurști', 'hot dog'],
  // Chicken (pui)
  ['piept de pui', 'chicken breast'],
  ['pulpa de pui', 'chicken thigh'],
  ['picioare de pui', 'chicken drumstick'],
  ['ciocan de pui', 'chicken drumstick'],
  ['aripioare de pui', 'chicken wing'],
  ['aripi de pui', 'chicken wing'],
  ['pui intreg', 'chicken'],
  ['pui întreg', 'chicken'],
  ['jumatate de pui', 'chicken'],
  ['jumătate de pui', 'chicken'],
  ['ficat de pui', 'chicken liver'],
  // Beef (vită)
  ['muschi de vita', 'beef tenderloin'],
  ['mușchi de vită', 'beef tenderloin'],
  ['antricot', 'ribeye'],
  ['vrabioara', 'sirloin'],
  ['vrăbioară', 'sirloin'],
  ['piept de vita', 'brisket'],
  ['piept de vită', 'brisket'],
  ['coada de vita', 'oxtail'],
  ['coadă de vită', 'oxtail'],
  ['carne tocata de vita', 'ground beef'],
  ['carne tocată de vită', 'ground beef'],
  ['vita tocata', 'ground beef'],
  ['vită tocată', 'ground beef'],
  ['ficat de vita', 'beef liver'],
  ['ficat de vită', 'beef liver'],
  // Lamb (miel)
  ['miel', 'lamb'],                         // Romanian lamb (not French honey)
  ['pulpa de miel', 'lamb leg'],
  ['umar de miel', 'lamb shoulder'],
  ['umăr de miel', 'lamb shoulder'],
  ['cotlet de miel', 'lamb chop'],
  ['muschi de miel', 'lamb rack'],
  ['mușchi de miel', 'lamb rack'],
  // Turkey & Duck
  ['curcan', 'turkey'],
  ['piept de curcan', 'turkey breast'],
  ['rata', 'duck'],
  ['rață', 'duck'],
  ['piept de rata', 'duck breast'],
  ['piept de rață', 'duck breast'],
  // Offal & cured
  ['ficat', 'liver'],
  ['rinichi', 'kidney'],
  ['sunculita', 'ham'],
  ['șuncuțiță', 'ham'],
  ['muschi file', 'pork loin'],
  ['mușchi file', 'pork loin'],
  ['slanina', 'bacon'],
  ['slănină', 'bacon'],
  ['kaiser', 'bacon'],
  ['prosciutto', 'prosciutto'],
  ['salam', 'salami'],
  ['parizer', 'hot dog'],

  // ── Romanian: dairy & eggs ───────────────────────────────────────────────
  ['branza topita', 'cream cheese'],
  ['brânză topită', 'cream cheese'],
  ['branza cu mucegai', 'blue cheese'],
  ['brânză cu mucegai', 'blue cheese'],
  ['branza galbena', 'cheese'],
  ['brânză galbenă', 'cheese'],
  ['telemea', 'feta'],
  ['branza telemea', 'feta'],
  ['brânză telemea', 'feta'],
  ['cascaval', 'gouda'],               // yellow cheese (closest match)
  ['cașcaval', 'gouda'],
  ['urda', 'ricotta'],                 // similar fresh cheese
  ['urdă', 'ricotta'],
  ['cas', 'cottage cheese'],
  ['caș', 'cottage cheese'],
  ['lapte batut', 'buttermilk'],
  ['lapte bătut', 'buttermilk'],
  ['lapte condensat', 'condensed milk'],
  ['lapte evaporat', 'evaporated milk'],
  ['lapte praf', 'milk'],
  ['frisca', 'whipping cream'],
  ['frișcă', 'whipping cream'],
  ['smantana pentru gatit', 'heavy cream'],
  ['smântână pentru gătit', 'heavy cream'],

  // ── Romanian: grains, legumes, starches ─────────────────────────────────
  ['naut', 'chickpeas'],
  ['năut', 'chickpeas'],
  ['linte rosie', 'red lentils'],
  ['linte roșie', 'red lentils'],
  ['linte verde', 'green lentils'],
  ['fasole alba', 'white beans'],
  ['fasole albă', 'white beans'],
  ['fasole neagra', 'black beans'],
  ['fasole neagră', 'black beans'],
  ['fasole boabe', 'beans'],
  ['mazare', 'peas'],
  ['mazăre', 'peas'],
  ['soia', 'soybeans'],
  ['quinoa', 'quinoa'],
  ['hrisce', 'buckwheat'],
  ['hrișcă', 'buckwheat'],
  ['mei', 'millet'],
  ['orz', 'barley'],
  ['grau', 'flour'],
  ['grâu', 'flour'],
  ['malai', 'cornmeal'],
  ['mălai', 'cornmeal'],
  ['gris', 'semolina'],
  ['griș', 'semolina'],
  ['paste', 'pasta'],
  ['taietei', 'noodles'],
  ['tăiței', 'noodles'],
  ['orez cu bob lung', 'long grain rice'],
  ['orez basmati', 'basmati rice'],
  ['orez cu bob rotund', 'arborio rice'],
  ['paine', 'bread'],
  ['pâine', 'bread'],
  ['franzela', 'bread'],
  ['franzelă', 'bread'],
  ['covrigi', 'pretzels'],
  ['biscuiti', 'crackers'],
  ['biscuiți', 'crackers'],
  ['pesmet', 'breadcrumbs'],           // already there ✓ keep for safety

  // ── Romanian: fruits ────────────────────────────────────────────────────
  ['portocala', 'orange'],
  ['portocală', 'orange'],
  ['portocale', 'orange'],
  ['mandarina', 'mandarin'],
  ['mandarină', 'mandarin'],
  ['grapefruit', 'grapefruit'],
  ['afine', 'blueberry'],
  ['coacaze', 'currant'],
  ['coacăze', 'currant'],
  ['coacaze negre', 'black currant'],
  ['mure', 'blackberry'],
  ['visine', 'sour cherry'],
  ['vișine', 'sour cherry'],
  ['cirese', 'cherry'],
  ['cireșe', 'cherry'],
  ['struguri', 'grape'],
  ['struguri rosii', 'red grape'],
  ['prune', 'plum'],
  ['prune uscate', 'prune'],
  ['caise', 'apricot'],
  ['smochine', 'fig'],
  ['smochine uscate', 'dried fig'],
  ['curmale', 'date'],
  ['banane', 'banana'],
  ['mango', 'mango'],
  ['ananas', 'pineapple'],
  ['papaya', 'papaya'],
  ['pepene verde', 'watermelon'],
  ['pepene galben', 'cantaloupe'],
  ['pepene', 'watermelon'],
  ['kiwi', 'kiwi'],
  ['cocos', 'coconut'],
  ['nucă de cocos', 'coconut'],
  ['nuca de cocos', 'coconut'],
  ['stafide', 'raisin'],
  ['avocado', 'avocado'],
  ['rodie', 'pomegranate'],
  ['gutui', 'quince'],
  ['nectarine', 'nectarine'],
  ['piersici', 'peach'],

  // ── Romanian: vegetables & produce ──────────────────────────────────────
  ['sfecla rosie', 'beet'],
  ['sfeclă roșie', 'beet'],
  ['napi', 'turnip'],
  ['pastarnac', 'parsnip'],
  ['păstârnac', 'parsnip'],
  ['hrean', 'horseradish'],
  ['ridichi', 'radish'],
  ['gulii', 'kohlrabi'],
  ['gulie', 'kohlrabi'],
  ['fenicul', 'fennel bulb'],
  ['salata', 'lettuce'],
  ['salată', 'lettuce'],
  ['rucola', 'arugula'],
  ['rucolă', 'arugula'],
  ['andive', 'endive'],
  ['stevie', 'chard'],
  ['mangold', 'chard'],
  ['muguri de soia', 'bean sprouts'],
  ['porumb dulce', 'corn'],
  ['porumb conserva', 'corn'],
  ['ardei capia', 'red pepper'],
  ['ardei kapia', 'red pepper'],
  ['ardei gras rosu', 'red bell pepper'],
  ['ardei gras galben', 'yellow bell pepper'],
  ['dovleac butternut', 'butternut squash'],
  ['dovleac plăcintă', 'pumpkin'],
  ['dovleac placinta', 'pumpkin'],
  ['varza de bruxelles', 'brussels sprouts'],
  ['varza de Bruxelles', 'brussels sprouts'],
  ['sparanghel', 'asparagus'],
  ['anghinare', 'artichoke'],
  ['nap', 'turnip'],
  ['ceapa esalota', 'shallot'],
  ['eșalotă', 'shallot'],
  ['esalota', 'shallot'],
  ['praz', 'leek'],
  ['ceapa de primavara', 'spring onion'],
  ['ceapă de primăvară', 'spring onion'],
  ['arpagic', 'spring onion'],
  ['usturoi verde', 'spring onion'],
  ['ciuperci champignon', 'white mushroom'],
  ['ciuperci portobello', 'portobello'],
  ['ciuperci shiitake', 'shiitake'],
  ['ciuperci porcini', 'porcini'],
  ['ciuperci uscate', 'dried mushroom'],

  // ── Romanian: nuts, seeds, oils ─────────────────────────────────────────
  ['nuca', 'walnuts'],
  ['nucă', 'walnuts'],
  ['nuci', 'walnuts'],
  ['nuci caju', 'cashews'],
  ['nuci de caju', 'cashews'],
  ['nuci de Brazilia', 'brazil nuts'],
  ['alune de padure', 'hazelnuts'],
  ['alune de pădure', 'hazelnuts'],
  ['alune', 'hazelnuts'],
  ['arahide', 'peanuts'],
  ['migdale feliate', 'sliced almonds'],
  ['nuci pecan', 'pecans'],
  ['fistic', 'pistachios'],
  ['seminte de susan', 'sesame seeds'],
  ['seminte de floarea soarelui', 'sunflower seeds'],
  ['seminte de dovleac', 'pumpkin seeds'],
  ['seminte de in', 'flaxseed'],
  ['seminte de chia', 'chia seeds'],
  ['seminte de mac', 'poppy seeds'],
  ['ulei de floarea soarelui', 'sunflower oil'],
  ['ulei de rapita', 'canola oil'],
  ['ulei de rapiță', 'canola oil'],
  ['ulei de cocos', 'coconut oil'],
  ['untura', 'lard'],
  ['untură', 'lard'],
  ['unt de arahide', 'peanut butter'],
  ['pasta de arahide', 'peanut butter'],

  // ── Romanian: sauces, condiments, pantry ────────────────────────────────
  ['sos de rosii', 'tomato sauce'],
  ['sos de roșii', 'tomato sauce'],
  ['piure de rosii', 'tomato puree'],
  ['piure de roșii', 'tomato puree'],
  ['rosii tocate', 'canned tomato'],
  ['roșii tocate', 'canned tomato'],
  ['rosii conserva', 'canned tomato'],
  ['roșii conservă', 'canned tomato'],
  ['bulion de rosii', 'tomato puree'],
  ['bulion de roșii', 'tomato puree'],
  ['bulion', 'tomato puree'],
  ['otet de mere', 'apple cider vinegar'],
  ['oțet de mere', 'apple cider vinegar'],
  ['otet balsamic', 'balsamic vinegar'],
  ['oțet balsamic', 'balsamic vinegar'],
  ['sos worcestershire', 'worcestershire sauce'],
  ['sos de soia', 'soy sauce'],
  ['miso', 'miso'],
  ['tahini', 'tahini'],
  ['pasta de susan', 'tahini'],
  ['maioneza', 'mayonnaise'],
  ['maioneză', 'mayonnaise'],
  ['mustar', 'mustard'],
  ['muștar', 'mustard'],
  ['mustar dijon', 'dijon mustard'],
  ['muștar Dijon', 'dijon mustard'],
  ['ketchup', 'ketchup'],
  ['sos iute', 'hot sauce'],
  ['ardei iute uscat', 'red pepper flakes'],
  ['capere', 'capers'],
  ['masline', 'olives'],
  ['măsline', 'olives'],
  ['masline negre', 'black olives'],
  ['măsline negre', 'black olives'],
  ['masline verzi', 'green olives'],
  ['măsline verzi', 'green olives'],
  ['cornichon', 'pickle'],
  ['cornichoni', 'pickle'],
  ['varza murata', 'sauerkraut'],
  ['varză murată', 'sauerkraut'],
  ['castraveti murati', 'pickle'],
  ['castraveți murați', 'pickle'],

  // ── Romanian: spices & herbs (additional) ──────────────────────────────
  ['ienibahar', 'allspice'],
  ['anason', 'anise'],
  ['anason stelat', 'star anise'],
  ['schinduf', 'fenugreek'],
  ['sofran', 'saffron'],
  ['șofran', 'saffron'],
  ['cuisoare', 'cloves'],
  ['cuișoare', 'cloves'],
  ['foi de dafin', 'bay leaves'],
  ['lamaie verde', 'lime'],
  ['lămâie verde', 'lime'],
  ['coaja de lamaie', 'lemon'],
  ['coajă de lămâie', 'lemon'],
  ['coaja de portocala', 'orange'],
  ['suc de portocale', 'orange'],
  ['suc de lamaie', 'lemon juice'],
  ['suc de lămâie', 'lemon juice'],
  ['vin rosu', 'red wine'],
  ['vin roșu', 'red wine'],
  ['vin alb', 'white wine'],
  ['bere', 'beer'],
  ['rom', 'rum'],
  ['coniac', 'brandy'],
  ['vodca', 'vodka'],
  ['votcă', 'vodka'],

  // ── Romanian: baking & sweets ───────────────────────────────────────────
  ['ciocolata neagra', 'dark chocolate'],
  ['ciocolată neagră', 'dark chocolate'],
  ['ciocolata cu lapte', 'milk chocolate'],
  ['ciocolată cu lapte', 'milk chocolate'],
  ['cacao', 'cocoa powder'],
  ['praf de cacao', 'cocoa powder'],
  ['zahar pudra', 'powdered sugar'],
  ['zahăr pudră', 'powdered sugar'],
  ['zahar vanilat', 'vanilla'],
  ['zahăr vanilat', 'vanilla'],
  ['sirop de artar', 'maple syrup'],
  ['sirop de arțar', 'maple syrup'],
  ['sirop de agave', 'agave'],
  ['miere de albine', 'honey'],
  ['jeleu', 'gelatin'],
  ['gelatina', 'gelatin'],
  ['gelatină', 'gelatin'],
  ['agar agar', 'agar agar'],
  ['amidon', 'cornstarch'],
  ['amidon de porumb', 'cornstarch'],

  // ═══════════════════════════════════════════════════════════════════════════
  // FRENCH (fr)
  // ═══════════════════════════════════════════════════════════════════════════
  ['ail', 'garlic'],
  ['basilic', 'basil'],
  ['beurre', 'butter'],
  ['carotte', 'carrot'],
  ['carottes', 'carrot'],
  ['champignon', 'mushroom'],
  ['champignons', 'mushroom'],
  ['citron', 'lemon'],
  ['citron vert', 'lime'],
  ['creme fraiche', 'sour cream'],
  ['epinards', 'spinach'],
  ['farine', 'flour'],
  ['fromage', 'cheese'],
  ['haricots', 'beans'],
  ['haricots verts', 'green beans'],
  ['huile', 'oil'],
  ['huile d olive', 'olive oil'],
  ["huile d'olive", 'olive oil'],
  ['jambon', 'ham'],
  ['lait', 'milk'],
  ['lentilles', 'lentils'],
  ['miel fr', 'honey'],    // "miel" in Romanian = lamb; French duplicate avoided
  ['oeuf', 'egg'],
  ['oeufs', 'eggs'],
  ['oignon', 'onion'],
  ['oignons', 'onion'],
  ['oignon rouge', 'red onion'],
  ['persil', 'parsley'],
  ['poivron', 'bell pepper'],
  ['poivron rouge', 'red pepper'],
  ['poivron vert', 'green pepper'],
  ['pomme', 'apple'],
  ['pommes', 'apple'],
  ['pomme de terre', 'potato'],
  ['pommes de terre', 'potato'],
  ['porc', 'pork'],
  ['poulet', 'chicken'],
  ['riz', 'rice'],
  ['sucre', 'sugar'],
  ['thon', 'tuna'],
  ['tomates', 'tomato'],
  ['concombre', 'cucumber'],
  ['chou', 'cabbage'],
  ['chou-fleur', 'cauliflower'],
  ['aubergine fr', 'eggplant'],
  ['courgette', 'zucchini'],
  ['courgettes', 'zucchini'],
  ['brocoli', 'broccoli'],
  ['fraise', 'strawberry'],
  ['fraises', 'strawberry'],
  ['framboises', 'raspberry'],
  ['saumon', 'salmon'],
  ['crevettes', 'shrimp'],
  ['boeuf', 'beef'],
  ['veau', 'veal'],
  ['agneau', 'lamb'],
  ['crème', 'cream'],
  ['yaourt', 'yogurt'],
  ['vinaigre', 'vinegar'],
  ['sel', 'salt'],
  ['poivre', 'black pepper'],
  ['cannelle', 'cinnamon'],
  ['coriandre', 'cilantro'],
  ['thym', 'thyme'],
  ['romarin', 'rosemary'],
  ['estragon', 'tarragon'],
  ['ciboulette', 'chives'],

  // ═══════════════════════════════════════════════════════════════════════════
  // SPANISH (es)
  // ═══════════════════════════════════════════════════════════════════════════
  ['aceite', 'oil'],
  ['aceite de oliva', 'olive oil'],
  ['ajo', 'garlic'],
  ['albahaca', 'basil'],
  ['arroz', 'rice'],
  ['atun', 'tuna'],
  ['azucar', 'sugar'],
  ['azucar morena', 'brown sugar'],
  ['berenjena', 'eggplant'],
  ['brocoli', 'broccoli'],
  ['calabacin', 'zucchini'],
  ['cebolla', 'onion'],
  ['cebolla roja', 'red onion'],
  ['cerdo', 'pork'],
  ['champiñones', 'mushroom'],
  ['cilantro', 'cilantro'],
  ['coliflor', 'cauliflower'],
  ['crema', 'cream'],
  ['fresa', 'strawberry'],
  ['fresas', 'strawberry'],
  ['frambuesas', 'raspberry'],
  ['harina', 'flour'],
  ['huevo', 'egg'],
  ['huevos', 'eggs'],
  ['jamon', 'ham'],
  ['judias verdes', 'green beans'],
  ['leche', 'milk'],
  ['lentejas', 'lentils'],
  ['limon', 'lemon'],
  ['lima', 'lime'],
  ['maiz', 'corn'],
  ['mantequilla', 'butter'],
  ['manzana', 'apple'],
  ['manzanas', 'apple'],
  ['miel es', 'honey'],
  ['naranja', 'orange'],
  ['patata', 'potato'],
  ['patatas', 'potato'],
  ['pepino', 'cucumber'],
  ['perejil', 'parsley'],
  ['pimiento', 'bell pepper'],
  ['pimiento rojo', 'red pepper'],
  ['pimiento verde', 'green pepper'],
  ['platano', 'banana'],
  ['pollo', 'chicken'],
  ['queso', 'cheese'],
  ['repollo', 'cabbage'],
  ['sal', 'salt'],
  ['salmon', 'salmon'],
  ['camarones', 'shrimp'],
  ['gambas', 'shrimp'],
  ['ternera', 'veal'],
  ['cordero', 'lamb'],
  ['res', 'beef'],
  ['carne molida', 'ground beef'],
  ['vinagre', 'vinegar'],
  ['yogur', 'yogurt'],
  ['zanahoria', 'carrot'],
  ['zanahorias', 'carrot'],
  ['canela', 'cinnamon'],
  ['tomillo', 'thyme'],
  ['romero', 'rosemary'],
  ['oregano es', 'oregano'],
  ['pimenton', 'paprika'],
  ['comino', 'cumin'],

  // ═══════════════════════════════════════════════════════════════════════════
  // ITALIAN (it)
  // ═══════════════════════════════════════════════════════════════════════════
  ['aglio', 'garlic'],
  ['basilico', 'basil'],
  ['broccoli', 'broccoli'],
  ['burro', 'butter'],
  ['carota', 'carrot'],
  ['carote', 'carrot'],
  ['cavolfiore', 'cauliflower'],
  ['cavolo', 'cabbage'],
  ['cipolla', 'onion'],
  ['cipolla rossa', 'red onion'],
  ['cipolle', 'onion'],
  ['fagioli', 'beans'],
  ['fagiolini', 'green beans'],
  ['farina', 'flour'],
  ['finocchio', 'fennel'],
  ['formaggio', 'cheese'],
  ['fragola', 'strawberry'],
  ['fragole', 'strawberry'],
  ['funghi', 'mushroom'],
  ['latte', 'milk'],
  ['lenticchie', 'lentils'],
  ['limone', 'lemon'],
  ['mais it', 'corn'],
  ['manzo', 'beef'],
  ['maiale', 'pork'],
  ['mele', 'apple'],
  ['melanzana', 'eggplant'],
  ['melanzane', 'eggplant'],
  ['miele', 'honey'],
  ['olio', 'oil'],
  ["olio d'oliva", 'olive oil'],
  ['olio di oliva', 'olive oil'],
  ['origano', 'oregano'],
  ['patate', 'potato'],
  ['peperone', 'bell pepper'],
  ['peperoni', 'bell pepper'],
  ['peperoncino', 'chili pepper'],
  ['piselli', 'peas'],
  ['pollo', 'chicken'],
  ['pomodoro', 'tomato'],
  ['pomodori', 'tomato'],
  ['prezzemolo', 'parsley'],
  ['prosciutto', 'ham'],
  ['riso', 'rice'],
  ['rosmarino', 'rosemary'],
  ['salmone', 'salmon'],
  ['gamberetti', 'shrimp'],
  ['agnello it', 'lamb'],
  ['vitello', 'veal'],
  ['spinaci', 'spinach'],
  ['tonno', 'tuna'],
  ['uova', 'eggs'],
  ['uovo', 'egg'],
  ['yogurt it', 'yogurt'],
  ['zucchero', 'sugar'],
  ['zucchina', 'zucchini'],
  ['zucchine', 'zucchini'],
  ['zucca', 'pumpkin'],
  ['aceto', 'vinegar'],
  ['sale', 'salt'],
  ['pepe', 'black pepper'],
  ['cannella', 'cinnamon'],
  ['prezzemolo it', 'parsley'],
  ['timo', 'thyme'],
  ['erba cipollina', 'chives'],
  ['panna', 'cream'],

  // ═══════════════════════════════════════════════════════════════════════════
  // GERMAN (de)
  // ═══════════════════════════════════════════════════════════════════════════
  ['apfel', 'apple'],
  ['äpfel', 'apple'],
  ['aubergine', 'eggplant'],
  ['blumenkohl', 'cauliflower'],
  ['bohnen', 'beans'],
  ['broccoli de', 'broccoli'],
  ['brokkoli', 'broccoli'],
  ['ei', 'egg'],
  ['eier', 'eggs'],
  ['erdbeere', 'strawberry'],
  ['erdbeeren', 'strawberry'],
  ['essig', 'vinegar'],
  ['fleisch', 'meat'],
  ['gurke', 'cucumber'],
  ['gurken', 'cucumber'],
  ['hackfleisch', 'ground beef'],
  ['hähnchen', 'chicken'],
  ['hühnchen', 'chicken'],
  ['huhn', 'chicken'],
  ['honig', 'honey'],
  ['karotte', 'carrot'],
  ['karotten', 'carrot'],
  ['käse', 'cheese'],
  ['kirsche', 'cherry'],
  ['kirschen', 'cherry'],
  ['knoblauch', 'garlic'],
  ['kohl', 'cabbage'],
  ['rotkohl', 'red cabbage'],
  ['lachs', 'salmon'],
  ['lamm', 'lamb'],
  ['lauch', 'leek'],
  ['linsen', 'lentils'],
  ['mais de', 'corn'],
  ['mehl', 'flour'],
  ['milch', 'milk'],
  ['möhre', 'carrot'],
  ['möhren', 'carrot'],
  ['öl', 'oil'],
  ['olivenöl', 'olive oil'],
  ['paprika de', 'bell pepper'],   // DE "Paprika" = bell pepper; generic "paprika" = spice
  ['rote paprika', 'red pepper'],
  ['grüne paprika', 'green pepper'],
  ['petersilie', 'parsley'],
  ['pilze', 'mushroom'],
  ['pute', 'turkey'],
  ['rahm', 'cream'],
  ['sahne', 'cream'],
  ['rind', 'beef'],
  ['rindfleisch', 'beef'],
  ['reis de', 'rice'],
  ['rosenkohl', 'brussels sprouts'],
  ['salz', 'salt'],
  ['schinken', 'ham'],
  ['schwein', 'pork'],
  ['schweinefleisch', 'pork'],
  ['spinat', 'spinach'],
  ['thunfisch', 'tuna'],
  ['tomate', 'tomato'],
  ['tomaten', 'tomato'],
  ['zwiebel', 'onion'],
  ['zwiebeln', 'onion'],
  ['rote zwiebel', 'red onion'],
  ['zucker', 'sugar'],
  ['zimt', 'cinnamon'],
  ['basilikum', 'basil'],
  ['rosmarin', 'rosemary'],
  ['thymian', 'thyme'],
  ['oregano de', 'oregano'],
  ['schnittlauch', 'chives'],
  ['ingwer', 'ginger'],
  ['joghurt', 'yogurt'],
  ['garnelen', 'shrimp'],
  ['erbsen', 'peas'],
  ['himbeere', 'raspberry'],
  ['himbeeren', 'raspberry'],
  ['banane', 'banana'],
  ['bananen', 'banana'],
  ['orange de', 'orange'],
  ['zitrone', 'lemon'],
  ['limette', 'lime'],

  // ═══════════════════════════════════════════════════════════════════════════
  // PORTUGUESE (pt)
  // ═══════════════════════════════════════════════════════════════════════════
  ['alho', 'garlic'],
  ['alho-porro', 'leek'],
  ['arroz pt', 'rice'],
  ['atum', 'tuna'],
  ['açúcar', 'sugar'],
  ['acucar', 'sugar'],
  ['batata', 'potato'],
  ['batatas', 'potato'],
  ['batata doce', 'sweet potato'],
  ['beringela', 'eggplant'],
  ['brocolo', 'broccoli'],
  ['brócolos', 'broccoli'],
  ['cebola', 'onion'],
  ['cebola roxa', 'red onion'],
  ['cenoura', 'carrot'],
  ['cenouras', 'carrot'],
  ['couve', 'cabbage'],
  ['couve-flor', 'cauliflower'],
  ['ervilhas', 'peas'],
  ['espinafre', 'spinach'],
  ['espinafres', 'spinach'],
  ['feijao', 'beans'],
  ['feijão', 'beans'],
  ['feijão verde', 'green beans'],
  ['farinha', 'flour'],
  ['frango', 'chicken'],
  ['leite', 'milk'],
  ['lentilhas', 'lentils'],
  ['limão', 'lemon'],
  ['limao', 'lemon'],
  ['manteiga', 'butter'],
  ['maçã', 'apple'],
  ['maca', 'apple'],
  ['mel', 'honey'],
  ['milho', 'corn'],
  ['morango', 'strawberry'],
  ['morangos', 'strawberry'],
  ['nata', 'cream'],
  ['ovo', 'egg'],
  ['ovos', 'eggs'],
  ['pepino pt', 'cucumber'],
  ['pimento', 'bell pepper'],
  ['pimento vermelho', 'red pepper'],
  ['queijo', 'cheese'],
  ['salmão', 'salmon'],
  ['sal pt', 'salt'],
  ['tomate pt', 'tomato'],
  ['tomates pt', 'tomato'],
  ['carne', 'meat'],
  ['carne de vaca', 'beef'],
  ['carne de porco', 'pork'],
  ['presunto', 'ham'],
  ['camarão', 'shrimp'],
  ['camarao', 'shrimp'],
  ['iogurte', 'yogurt'],
  ['vinagre pt', 'vinegar'],
  ['canela pt', 'cinnamon'],
  ['coentros', 'cilantro'],
  ['salsa', 'parsley'],
  ['manjericão', 'basil'],
  ['alecrim', 'rosemary'],
  ['tomilho', 'thyme'],

  // ═══════════════════════════════════════════════════════════════════════════
  // DUTCH (nl)
  // ═══════════════════════════════════════════════════════════════════════════
  ['aardappel', 'potato'],
  ['aardappelen', 'potato'],
  ['aardbeien', 'strawberry'],
  ['appel', 'apple'],
  ['appels', 'apple'],
  ['bloemkool', 'cauliflower'],
  ['boontjes', 'green beans'],
  ['brocoli nl', 'broccoli'],
  ['broccoli nl', 'broccoli'],
  ['champignons nl', 'mushroom'],
  ['ei nl', 'egg'],
  ['eieren', 'eggs'],
  ['erwten', 'peas'],
  ['garnaaltjes', 'shrimp'],
  ['garnalen', 'shrimp'],
  ['kip', 'chicken'],
  ['knoflook', 'garlic'],
  ['komkommer', 'cucumber'],
  ['lamsvlees', 'lamb'],
  ['melk', 'milk'],
  ['meel', 'flour'],
  ['mais nl', 'corn'],
  ['olie', 'oil'],
  ['olijfolie', 'olive oil'],
  ['paprika nl', 'bell pepper'],
  ['rode paprika', 'red pepper'],
  ['peer', 'pear'],
  ['peren', 'pear'],
  ['peterselie', 'parsley'],
  ['prei', 'leek'],
  ['rijst', 'rice'],
  ['rundvlees', 'beef'],
  ['sla', 'lettuce'],
  ['slagroom', 'cream'],
  ['spinazie', 'spinach'],
  ['suiker', 'sugar'],
  ['ui', 'onion'],
  ['uien', 'onion'],
  ['rode ui', 'red onion'],
  ['varkensvlees', 'pork'],
  ['wortel', 'carrot'],
  ['wortelen', 'carrot'],
  ['yoghurt nl', 'yogurt'],
  ['zout', 'salt'],
  ['zuurkool', 'sauerkraut'],
  ['boter', 'butter'],
  ['honing', 'honey'],
  ['citroen', 'lemon'],
  ['basilicum', 'basil'],
  ['tijm', 'thyme'],
  ['rozemarijn', 'rosemary'],
  ['koriander nl', 'cilantro'],
  ['kardemom', 'cardamom'],
  ['kaneel', 'cinnamon'],
  ['azijn', 'vinegar'],
  ['kaas', 'cheese'],
  ['ham nl', 'ham'],
  ['zalm', 'salmon'],
  ['tonijn', 'tuna'],

  // ═══════════════════════════════════════════════════════════════════════════
  // POLISH (pl)
  // ═══════════════════════════════════════════════════════════════════════════
  ['cebula', 'onion'],
  ['cukier', 'sugar'],
  ['czosnek', 'garlic'],
  ['dynia', 'pumpkin'],
  ['fasola', 'beans'],
  ['groch', 'peas'],
  ['herbata', 'tea'],
  ['jajko', 'egg'],
  ['jajka', 'eggs'],
  ['kapusta', 'cabbage'],
  ['kasza', 'groats'],
  ['kurczak', 'chicken'],
  ['łosoś', 'salmon'],
  ['losос', 'salmon'],
  ['maka', 'flour'],
  ['mąka', 'flour'],
  ['marchew', 'carrot'],
  ['marchewka', 'carrot'],
  ['maslo', 'butter'],
  ['masło', 'butter'],
  ['mleko', 'milk'],
  ['miod', 'honey'],
  ['miód', 'honey'],
  ['ogórek', 'cucumber'],
  ['ogorek', 'cucumber'],
  ['oliwa z oliwek', 'olive oil'],
  ['papryka', 'bell pepper'],
  ['papryka czerwona', 'red pepper'],
  ['pietruszka', 'parsley'],
  ['pieczarki', 'mushroom'],
  ['pomidor', 'tomato'],
  ['pomidory', 'tomato'],
  ['por', 'leek'],
  ['ryba', 'fish'],
  ['ryż', 'rice'],
  ['ryz', 'rice'],
  ['ser', 'cheese'],
  ['sól', 'salt'],
  ['sol pl', 'salt'],
  ['szynka', 'ham'],
  ['szynki', 'ham'],
  ['truskawki', 'strawberry'],
  ['wieprzowina', 'pork'],
  ['wołowina', 'beef'],
  ['wolowina', 'beef'],
  ['ziemniaki', 'potato'],
  ['ziemniak', 'potato'],
  ['jogurt', 'yogurt'],
  ['olej', 'oil'],
  ['cynamon', 'cinnamon'],
  ['bazylia', 'basil'],
  ['tymianek', 'thyme'],
  ['rozmaryn', 'rosemary'],
  ['koperek', 'dill'],
  ['kolendra', 'cilantro'],
  ['ocet', 'vinegar'],
  ['smietana', 'sour cream'],
  ['śmietana', 'sour cream'],
  ['krewetki', 'shrimp'],

  // ═══════════════════════════════════════════════════════════════════════════
  // CZECH (cs) & SLOVAK (sk) — many words overlap
  // ═══════════════════════════════════════════════════════════════════════════
  ['brambory', 'potato'],
  ['brambor', 'potato'],
  ['brokolice', 'broccoli'],
  ['cibule', 'onion'],
  ['cesnek', 'garlic'],
  ['česnek', 'garlic'],
  ['cukr', 'sugar'],
  ['fazole', 'beans'],
  ['hrách', 'peas'],
  ['hrach', 'peas'],
  ['houby', 'mushroom'],
  ['houba', 'mushroom'],
  ['hruška', 'pear'],
  ['hrubka', 'pear'],
  ['jablko', 'apple'],
  ['jablka', 'apple'],
  ['jahody', 'strawberry'],
  ['jahoda', 'strawberry'],
  ['jogurt cz', 'yogurt'],
  ['kachna', 'duck'],
  ['kapusta cz', 'cabbage'],
  ['kuřecí', 'chicken'],
  ['kuře', 'chicken'],
  ['kure', 'chicken'],
  ['kyselá smetana', 'sour cream'],
  ['losos', 'salmon'],
  ['maso', 'meat'],
  ['máslo', 'butter'],
  ['maslo sk', 'butter'],
  ['mléko', 'milk'],
  ['mleko sk', 'milk'],
  ['med', 'honey'],
  ['mouka', 'flour'],
  ['múka', 'flour'],
  ['mrkev', 'carrot'],
  ['okurka', 'cucumber'],
  ['pepř', 'black pepper'],
  ['pepr', 'black pepper'],
  ['petržel', 'parsley'],
  ['rajče', 'tomato'],
  ['rajčata', 'tomato'],
  ['rýže', 'rice'],
  ['ryža', 'rice'],
  ['smetana', 'cream'],
  ['sůl', 'salt'],
  ['sol cz', 'salt'],
  ['šunka', 'ham'],
  ['sunka sk', 'ham'],
  ['treska', 'cod'],
  ['tuňák', 'tuna'],
  ['tunak', 'tuna'],
  ['vejce', 'egg'],
  ['vejcích', 'eggs'],
  ['vepřové', 'pork'],
  ['veprove', 'pork'],
  ['hovězí', 'beef'],
  ['hovezi', 'beef'],
  ['zelí', 'cabbage'],
  ['špenát', 'spinach'],
  ['spenat sk', 'spinach'],

  // ═══════════════════════════════════════════════════════════════════════════
  // HUNGARIAN (hu)
  // ═══════════════════════════════════════════════════════════════════════════
  ['alma', 'apple'],
  ['almák', 'apple'],
  ['burgonya', 'potato'],
  ['citrom', 'lemon'],
  ['cukor', 'sugar'],
  ['csirke', 'chicken'],
  ['fokhagyma', 'garlic'],
  ['gomba', 'mushroom'],
  ['hagyma', 'onion'],
  ['vörös hagyma', 'red onion'],
  ['joghurt hu', 'yogurt'],
  ['karalábé', 'kohlrabi'],
  ['kolbász', 'sausage'],
  ['liszt', 'flour'],
  ['marhahús', 'beef'],
  ['marhahus', 'beef'],
  ['méz', 'honey'],
  ['mez hu', 'honey'],
  ['paprikás csirke', 'chicken paprikash'],
  ['paprika hu', 'bell pepper'],
  ['piros paprika', 'red pepper'],
  ['petrezselyem', 'parsley'],
  ['rizs', 'rice'],
  ['sárgarépa', 'carrot'],
  ['sargarepa', 'carrot'],
  ['sertéshús', 'pork'],
  ['serteshus', 'pork'],
  ['só', 'salt'],
  ['so hu', 'salt'],
  ['spenót', 'spinach'],
  ['spenot', 'spinach'],
  ['szalonna', 'bacon'],
  ['tejföl', 'sour cream'],
  ['tejfol', 'sour cream'],
  ['tej', 'milk'],
  ['tojás', 'egg'],
  ['tojas', 'egg'],
  ['tojások', 'eggs'],
  ['turóc', 'cottage cheese'],
  ['uborka', 'cucumber'],
  ['vaj', 'butter'],
  ['krumpli', 'potato'],
  ['paradicsom', 'tomato'],
  ['eper', 'strawberry'],
  ['málna', 'raspberry'],
  ['banán', 'banana'],
  ['lazac', 'salmon'],
  ['tonhal', 'tuna'],
  ['garnéla', 'shrimp'],
  ['bárány', 'lamb'],
  ['sajt', 'cheese'],
  ['sonka', 'ham'],
  ['ecet', 'vinegar'],
  ['olívaolaj', 'olive oil'],
  ['fahéj', 'cinnamon'],
  ['bazsalikom', 'basil'],
  ['kakukkfű', 'thyme'],
  ['rozmaring', 'rosemary'],
  ['kömény', 'caraway'],
  ['tejszín', 'cream'],
  ['zöldbab', 'green beans'],
  ['borsó', 'peas'],

  // ═══════════════════════════════════════════════════════════════════════════
  // SWEDISH (sv)
  // ═══════════════════════════════════════════════════════════════════════════
  ['ägg', 'egg'],
  ['äggvita', 'egg white'],
  ['äpple', 'apple'],
  ['äpplen', 'apple'],
  ['apelsin', 'orange'],
  ['basilika sv', 'basil'],
  ['blomkål', 'cauliflower'],
  ['bönor', 'beans'],
  ['broccoli sv', 'broccoli'],
  ['citron sv', 'lemon'],
  ['dill sv', 'dill'],
  ['fläskkött', 'pork'],
  ['gurka sv', 'cucumber'],
  ['gröna bönor', 'green beans'],
  ['grönsaker', 'vegetables'],
  ['grädde', 'cream'],
  ['ärtor', 'peas'],
  ['hallon', 'raspberry'],
  ['jordgubbar', 'strawberry'],
  ['jordgubbe', 'strawberry'],
  ['kanel sv', 'cinnamon'],
  ['kyckling', 'chicken'],
  ['kött', 'meat'],
  ['lamm sv', 'lamb'],
  ['lax', 'salmon'],
  ['lök', 'onion'],
  ['rödlök', 'red onion'],
  ['lins', 'lentils'],
  ['linser', 'lentils'],
  ['mjöl', 'flour'],
  ['mjölk', 'milk'],
  ['morot', 'carrot'],
  ['morötter', 'carrot'],
  ['nötköttsfärs', 'ground beef'],
  ['nötkött', 'beef'],
  ['olja', 'oil'],
  ['olivolja', 'olive oil'],
  ['ost sv', 'cheese'],
  ['paprika sv', 'bell pepper'],
  ['persilja', 'parsley'],
  ['potatis', 'potato'],
  ['ris sv', 'rice'],
  ['röd paprika', 'red pepper'],
  ['rödbeta', 'beet'],
  ['salt sv', 'salt'],
  ['skinka', 'ham'],
  ['socker', 'sugar'],
  ['spenat', 'spinach'],
  ['svamp', 'mushroom'],
  ['tomat', 'tomato'],
  ['tomater', 'tomato'],
  ['tonfisk', 'tuna'],
  ['vitlök', 'garlic'],
  ['yoghurt sv', 'yogurt'],
  ['smör', 'butter'],
  ['honung', 'honey'],
  ['selleri', 'celery'],
  ['rökt lax', 'smoked salmon'],
  ['räkor', 'shrimp'],
  ['koriander sv', 'cilantro'],
  ['timjan', 'thyme'],
  ['rosmarin sv', 'rosemary'],
  ['ingefära', 'ginger'],
  ['gräddfil', 'sour cream'],

  // ═══════════════════════════════════════════════════════════════════════════
  // DANISH (da) & NORWEGIAN (no) — highly similar
  // ═══════════════════════════════════════════════════════════════════════════
  ['æble', 'apple'],
  ['æbler', 'apple'],
  ['asparges', 'asparagus'],
  ['blomkål da', 'cauliflower'],
  ['broccoli da', 'broccoli'],
  ['citron da', 'lemon'],
  ['dild', 'dill'],
  ['fårekød', 'lamb'],
  ['gulerod', 'carrot'],
  ['gulerødder', 'carrot'],
  ['gulerøtter', 'carrot'],
  ['hvidkål', 'cabbage'],
  ['hvidløg', 'garlic'],
  ['hvitløk', 'garlic'],
  ['jordbær', 'strawberry'],
  ['kanel da', 'cinnamon'],
  ['kartofler', 'potato'],
  ['kylling', 'chicken'],
  ['laks da', 'salmon'],
  ['løg', 'onion'],
  ['rødløg', 'red onion'],
  ['linser da', 'lentils'],
  ['mel da', 'flour'],
  ['mælk', 'milk'],
  ['melk', 'milk'],
  ['nøddekød', 'beef'],
  ['olie da', 'oil'],
  ['olivenolie', 'olive oil'],
  ['olivenoljer', 'olive oil'],
  ['persille', 'parsley'],
  ['peber', 'black pepper'],
  ['ris da', 'rice'],
  ['rødbede', 'beet'],
  ['rødkål', 'red cabbage'],
  ['salt da', 'salt'],
  ['svinekød', 'pork'],
  ['svineköd', 'pork'],
  ['svamp da', 'mushroom'],
  ['sopp', 'mushroom'],
  ['sukker', 'sugar'],
  ['tomat da', 'tomato'],
  ['tomater da', 'tomato'],
  ['torsk', 'cod'],
  ['tunfisk', 'tuna'],
  ['æg', 'egg'],
  ['smør', 'butter'],
  ['honning', 'honey'],
  ['fløde', 'cream'],
  ['fløte', 'cream'],
  ['spinat da', 'spinach'],
  ['basilikum da', 'basil'],
  ['timian', 'thyme'],
  ['rosmarin da', 'rosemary'],
  ['koriander da', 'cilantro'],
  ['eddike', 'vinegar'],
  ['reker', 'shrimp'],
  ['rejer', 'shrimp'],
  ['agurk', 'cucumber'],
  ['paprika da', 'bell pepper'],
  ['ost da', 'cheese'],
  ['skinke', 'ham'],
  ['yoghurt da', 'yogurt'],
  ['ingefær', 'ginger'],
  ['erter', 'peas'],
  ['ærter', 'peas'],

  // ═══════════════════════════════════════════════════════════════════════════
  // FINNISH (fi)
  // ═══════════════════════════════════════════════════════════════════════════
  ['appelsiini', 'orange'],
  ['banaani', 'banana'],
  ['brokkoli fi', 'broccoli'],
  ['herkkusieni', 'mushroom'],
  ['hunaja', 'honey'],
  ['jauhot', 'flour'],
  ['jogurtti', 'yogurt'],
  ['juusto', 'cheese'],
  ['kaali', 'cabbage'],
  ['kana', 'chicken'],
  ['kananmuna', 'egg'],
  ['kananmunat', 'eggs'],
  ['kinkku', 'ham'],
  ['kirsikat', 'cherry'],
  ['kurkku fi', 'cucumber'],
  ['kyynelkaali', 'brussels sprouts'],
  ['lohi', 'salmon'],
  ['maitio', 'milk'],
  ['maito', 'milk'],
  ['mansikka', 'strawberry'],
  ['mansikat', 'strawberry'],
  ['naudan liha', 'beef'],
  ['naudanliha', 'beef'],
  ['öljy', 'oil'],
  ['oliivi öljy', 'olive oil'],
  ['oliiviöljy', 'olive oil'],
  ['paprika fi', 'bell pepper'],
  ['persilja', 'parsley'],
  ['pinaatti', 'spinach'],
  ['porkkana', 'carrot'],
  ['porkkanat', 'carrot'],
  ['riisi', 'rice'],
  ['sianliha', 'pork'],
  ['sienet', 'mushroom'],
  ['sipuli', 'onion'],
  ['sokeriherne', 'sugar snap peas'],
  ['sokeri', 'sugar'],
  ['suola', 'salt'],
  ['tomaatti', 'tomato'],
  ['tomaatit', 'tomato'],
  ['tonnikala', 'tuna'],
  ['voi', 'butter'],
  ['valkosipuli', 'garlic'],
  ['vihreät pavut', 'green beans'],
  ['peruna', 'potato'],
  ['perunat', 'potato'],
  ['omena', 'apple'],
  ['omenat', 'apple'],
  ['kerma', 'cream'],
  ['hapankerma', 'sour cream'],
  ['basilika fi', 'basil'],
  ['timjami', 'thyme'],
  ['rosmariini', 'rosemary'],
  ['kaneli', 'cinnamon'],
  ['inkivääri', 'ginger'],
  ['katkarapu', 'shrimp'],
  ['katkaravut', 'shrimp'],
  ['etikka', 'vinegar'],

  // ═══════════════════════════════════════════════════════════════════════════
  // GREEK – romanised common spellings (el)
  // ═══════════════════════════════════════════════════════════════════════════
  ['agginara', 'artichoke'],
  ['angouri', 'cucumber'],
  ['arni', 'lamb'],
  ['avgo', 'egg'],
  ['avga', 'eggs'],
  ['domata', 'tomato'],
  ['domaties', 'tomato'],
  ['elaia', 'olive'],
  ['elaiolatho', 'olive oil'],
  ['feta', 'feta cheese'],
  ['gala', 'milk'],
  ['garida', 'shrimp'],
  ['garides', 'shrimp'],
  ['kotopoulo', 'chicken'],
  ['kremidi', 'onion'],
  ['lemoni', 'lemon'],
  ['loukanika', 'sausage'],
  ['manitari', 'mushroom'],
  ['manitaria', 'mushroom'],
  ['melitzana', 'eggplant'],
  ['melitzanes', 'eggplant'],
  ['moscharaki', 'veal'],
  ['mpanana', 'banana'],
  ['mprikola', 'broccoli'],
  ['ntomata', 'tomato'],
  ['ntomaties', 'tomato'],
  ['patata', 'potato'],
  ['patates', 'potato'],
  ['piperia', 'bell pepper'],
  ['piperies', 'bell pepper'],
  ['psari', 'fish'],
  ['rizi', 'rice'],
  ['saltsa', 'sauce'],
  ['skordalia', 'garlic sauce'],
  ['skordo', 'garlic'],
  ['spanaki', 'spinach'],
  ['stafyli', 'grape'],
  ['tyri', 'cheese'],
  ['zacharh', 'sugar'],
  ['zachari', 'sugar'],
  ['zacharini', 'zucchini'],
  ['kounoupidi', 'cauliflower'],
  ['lahaniki', 'vegetables'],
  ['aginares', 'artichoke'],
  ['alogo', 'horse'],
  ['fasolia', 'beans'],
  ['kolokythaki', 'zucchini'],
  ['lathi', 'oil'],
  ['mavro piperi', 'black pepper'],
  ['almyro', 'salt'],
  ['voutiro', 'butter'],
  ['meli', 'honey'],
  ['rigan', 'oregano'],

  // ═══════════════════════════════════════════════════════════════════════════
  // CROATIAN (hr) / SERBIAN romanised (sr) / SLOVENIAN (sl)
  // ═══════════════════════════════════════════════════════════════════════════
  ['bijeli luk', 'garlic'],
  ['brokula', 'broccoli'],
  ['crveni luk', 'red onion'],
  ['gljive', 'mushroom'],
  ['govedina', 'beef'],
  ['grašak', 'peas'],
  ['jaje', 'egg'],
  ['jaja', 'eggs'],
  ['junetina', 'beef'],
  ['karfiol', 'cauliflower'],
  ['krumpir', 'potato'],
  ['krumpiri', 'potato'],
  ['kukuruz', 'corn'],
  ['losos hr', 'salmon'],
  ['luk', 'onion'],
  ['mlijeko', 'milk'],
  ['mleko sr', 'milk'],
  ['maslinovo ulje', 'olive oil'],
  ['med hr', 'honey'],
  ['paprika hr', 'bell pepper'],
  ['pecurke', 'mushroom'],
  ['peršin', 'parsley'],
  ['piletina', 'chicken'],
  ['pileće meso', 'chicken'],
  ['rajčica', 'tomato'],
  ['rajčice', 'tomato'],
  ['riža', 'rice'],
  ['slanina', 'bacon'],
  ['sol hr', 'salt'],
  ['špinat', 'spinach'],
  ['šunka hr', 'ham'],
  ['svinjsko meso', 'pork'],
  ['svinjina', 'pork'],
  ['šećer', 'sugar'],
  ['secer', 'sugar'],
  ['tikvica', 'zucchini'],
  ['ulje', 'oil'],
  ['jabuka', 'apple'],
  ['jagoda', 'strawberry'],
  ['maslac', 'butter'],
  ['mrkva', 'carrot'],
  ['krastavac', 'cucumber'],
  ['jogurt hr', 'yogurt'],
  ['celer', 'celery'],
  ['poriluk', 'leek'],
  ['blitva', 'chard'],
  ['češnjak', 'garlic'],
  ['majčina dušica', 'thyme'],
  ['ružmarin', 'rosemary'],
  ['bosiljak', 'basil'],
  ['ocet hr', 'vinegar'],
  ['vrhnje', 'cream'],
  ['kiselo vrhnje', 'sour cream'],

  // ═══════════════════════════════════════════════════════════════════════════
  // BULGARIAN – romanised (bg)
  // ═══════════════════════════════════════════════════════════════════════════
  ['chushki', 'bell pepper'],
  ['cherveni chushki', 'red pepper'],
  ['domati', 'tomato'],
  ['domat', 'tomato'],
  ['gotsvari', 'parsley'],
  ['kartofi bg', 'potato'],
  ['krastavitsa', 'cucumber'],
  ['lyutika', 'chili pepper'],
  ['maslo bg', 'butter'],
  ['med bg', 'honey'],
  ['mleko bg', 'milk'],
  ['morkov', 'carrot'],
  ['morkovi', 'carrot'],
  ['orientalski podpravki', 'spices'],
  ['pechurki', 'mushroom'],
  ['piletle', 'chicken'],
  ['prase', 'pork'],
  ['prasetina', 'pork'],
  ['riba', 'fish'],
  ['salat', 'lettuce'],
  ['svinetina', 'pork'],
  ['syunek', 'ham'],
  ['teleshko', 'beef'],
  ['tykvichka', 'zucchini'],
  ['zahar bg', 'sugar'],
  ['zelenchutsi', 'vegetables'],
  ['zyalo zelenilo', 'herbs'],

  // ═══════════════════════════════════════════════════════════════════════════
  // LITHUANIAN (lt) / LATVIAN (lv) / ESTONIAN (et)
  // ═══════════════════════════════════════════════════════════════════════════
  ['agurkas', 'cucumber'],
  ['agurki', 'cucumber'],
  ['baklažanas', 'eggplant'],
  ['brokoliai', 'broccoli'],
  ['burokėliai', 'beet'],
  ['česnaka', 'garlic'],
  ['česnakai', 'garlic'],
  ['dārzeņi', 'vegetables'],
  ['kartupeļi', 'potato'],
  ['kāposti', 'cabbage'],
  ['kiaušinis', 'egg'],
  ['kiaušiniai', 'eggs'],
  ['kreiviukai', 'shrimp'],
  ['lauki', 'leek'],
  ['lašiša', 'salmon'],
  ['miltai', 'flour'],
  ['milts', 'flour'],
  ['medus', 'honey'],
  ['piens', 'milk'],
  ['pienas', 'milk'],
  ['pipar', 'black pepper'],
  ['pipiras', 'black pepper'],
  ['pomidoras', 'tomato'],
  ['pomidorai', 'tomato'],
  ['rian', 'carrot'],
  ['siers', 'cheese'],
  ['sūris', 'cheese'],
  ['sool', 'salt'],
  ['sāls', 'salt'],
  ['sviestas', 'butter'],
  ['sviests', 'butter'],
  ['špinatai', 'spinach'],
  ['ūkiskos', 'farm'],
  ['vistas gaļa', 'chicken'],
  ['vista', 'chicken'],
  ['viščiukai', 'chicken'],
  ['Küüslauk', 'garlic'],
  ['kuuslauk', 'garlic'],
  ['porgand', 'carrot'],
  ['kurk et', 'cucumber'],
  ['kapsas', 'cabbage'],
  ['munad', 'eggs'],
  ['muna', 'egg'],
  ['piim', 'milk'],
  ['jahu', 'flour'],
  ['suhkur', 'sugar'],
  ['mesi', 'honey'],
  ['voi', 'butter'],
  ['juust', 'cheese'],
  ['liha', 'meat'],
  ['sealiha', 'pork'],
  ['veiseliha', 'beef'],
  ['kanafileet', 'chicken breast'],
  ['tomat', 'tomato'],
  ['tomatid', 'tomato'],
  ['sibul', 'onion'],
  ['riis et', 'rice'],
  ['seened', 'mushroom'],
  ['krevettid', 'shrimp'],
  ['lõhe', 'salmon'],

  // ═══════════════════════════════════════════════════════════════════════════
  // TURKISH (tr)
  // ═══════════════════════════════════════════════════════════════════════════
  ['balık', 'fish'],
  ['balik', 'fish'],
  ['bezelye', 'peas'],
  ['biber', 'bell pepper'],
  ['kırmızı biber', 'red pepper'],
  ['kirmizi biber', 'red pepper'],
  ['çarliston biber', 'green pepper'],
  ['sarımsak', 'garlic'],
  ['sarimisak', 'garlic'],
  ['domates', 'tomato'],
  ['elma', 'apple'],
  ['elmalar', 'apple'],
  ['fasulye tr', 'beans'],
  ['havuç', 'carrot'],
  ['havuc', 'carrot'],
  ['ıspanak', 'spinach'],
  ['ispanak', 'spinach'],
  ['jambon tr', 'ham'],
  ['kabak', 'zucchini'],
  ['karnabahar', 'cauliflower'],
  ['kereviz', 'celery'],
  ['kıyma', 'ground beef'],
  ['kiyma', 'ground beef'],
  ['kuzu eti', 'lamb'],
  ['limon tr', 'lemon'],
  ['makarna', 'pasta'],
  ['mantar', 'mushroom'],
  ['mısır', 'corn'],
  ['misir', 'corn'],
  ['nohut', 'chickpeas'],
  ['patates', 'potato'],
  ['peynir', 'cheese'],
  ['pirinç', 'rice'],
  ['pirinc', 'rice'],
  ['pırasa', 'leek'],
  ['pirasa', 'leek'],
  ['salatalık', 'cucumber'],
  ['salatalik', 'cucumber'],
  ['sardalya', 'sardine'],
  ['soğan', 'onion'],
  ['sogan', 'onion'],
  ['süt', 'milk'],
  ['sut tr', 'milk'],
  ['tavuk', 'chicken'],
  ['tereyağı', 'butter'],
  ['tereyagi', 'butter'],
  ['un', 'flour'],
  ['yumurta', 'egg'],
  ['yumurtalar', 'eggs'],
  ['zeytin yağı', 'olive oil'],
  ['zeytin yagi', 'olive oil'],
  ['zeytinyağı', 'olive oil'],
  ['zeytinyagi', 'olive oil'],
  ['bal', 'honey'],
  ['şeker', 'sugar'],
  ['seker tr', 'sugar'],
  ['tuz', 'salt'],
  ['fırın', 'oven'],
  ['sığır eti', 'beef'],
  ['sigir eti', 'beef'],
  ['domuz eti', 'pork'],
  ['balık filetosu', 'fish fillet'],
  ['somon', 'salmon'],
  ['karides', 'shrimp'],
  ['krem şanti', 'whipped cream'],
  ['yoğurt', 'yogurt'],
  ['yogurt tr', 'yogurt'],
  ['tarçın', 'cinnamon'],
  ['tarcin', 'cinnamon'],
  ['fesleğen', 'basil'],
  ['feslegen', 'basil'],
  ['kekik', 'thyme'],
  ['biberiye', 'rosemary'],
  ['kişniş', 'cilantro'],
  ['kisnis', 'cilantro'],
  ['sirke', 'vinegar'],
  ['ekşi krema', 'sour cream'],
  ['elma sirkesi', 'apple cider vinegar'],
  ['narenciye', 'citrus'],

  // ═══════════════════════════════════════════════════════════════════════════
  // CROSS-LANGUAGE HOMOGRAPHS
  // Words identical in multiple languages, canonical value is the same.
  // Listed once here to avoid TypeScript duplicate-key errors.
  // ═══════════════════════════════════════════════════════════════════════════
  ['tomate', 'tomato'],          // RO · FR · ES · IT · DE · PT
  // ['miel', 'honey'],          // FR · ES — conflicts with RO "miel" = lamb; RO wins (Romanian site)
  ['patata', 'potato'],          // ES · IT · EL
  ['farina', 'flour'],           // IT (also farine FR — different key)
  ['pollo', 'chicken'],          // ES · IT
  ['courgette', 'zucchini'],     // FR · EN-GB
  ['courgettes', 'zucchini'],    // FR plural · EN-GB plural
  ['broccoli', 'broccoli'],      // IT · EN plural
  ['yogurt', 'yogurt'],          // EN · various
  ['oregano', 'oregano'],        // EN · various
  ['cilantro', 'cilantro'],      // EN · ES
  // ['salsa', 'sauce'],         // ES · IT overlap — conflicts with IT "salsa" = parsley
  ['paprika', 'paprika'],        // EN cooking term (spice, not bell pepper)

  // ═══════════════════════════════════════════════════════════════════════════
  // COMMON INFORMAL / ALTERNATE ENGLISH SPELLINGS
  // ═══════════════════════════════════════════════════════════════════════════
  ['aubergine', 'eggplant'],
  ['capsicum', 'bell pepper'],
  ['coriander', 'cilantro'],
  ['mince', 'ground beef'],
  ['minced beef', 'ground beef'],
  ['minced meat', 'ground meat'],
  ['rocket', 'arugula'],
  ['spring onion', 'scallion'],
  ['spring onions', 'scallion'],
  ['swede', 'rutabaga'],
  ['turnip', 'turnip'],
  ['double cream', 'heavy cream'],
  ['single cream', 'light cream'],
  ['streaky bacon', 'bacon'],
  ['back bacon', 'bacon'],
  ['rasher', 'bacon'],
  ['rasher of bacon', 'bacon'],
  ['joint', 'roast'],
  ['mince pie', 'meat pie'],
  ['prawn', 'shrimp'],
  ['prawns', 'shrimp'],
  ['king prawn', 'jumbo shrimp'],
  ['courgetti', 'zucchini noodles'],
  ['mangetout', 'snow peas'],
  ['mange tout', 'snow peas'],
  ['cos lettuce', 'romaine lettuce'],
  ['gem lettuce', 'romaine lettuce'],
  ['tenderstem', 'broccolini'],
  ['pak choi', 'bok choy'],
  ['pak choy', 'bok choy'],
  ['spring greens', 'collard greens'],
  ['chilli', 'chili pepper'],
  ['chillies', 'chili pepper'],
]);

// ─────────────────────────────────────────────────────────────────────────────

/**
 * Expand a search query by resolving any known aliases to their English canonical.
 * Returns all unique terms (original + resolved canonicals) for use in search scoring.
 *
 * Examples:
 *   expandSearchTerms("ardei rosii")     → ["ardei","rosii","pepper","tomato"]
 *   expandSearchTerms("poivron rouge")   → ["poivron","rouge","red pepper","red","pepper","bell pepper"]
 *   expandSearchTerms("hühnchen")        → ["hühnchen","chicken"]
 */
export function expandSearchTerms(query: string): string[] {
  const raw = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  // Strip diacritics so "măsline" matches "masline" in dictionary
  const tokens = raw.map(t => stripDiacritics(t));
  const expanded = new Set<string>([...raw, ...tokens]);

  // 1. Try full phrase
  const fullPhrase = tokens.join(' ');
  const phraseMatch = INGREDIENT_ALIASES[fullPhrase];
  if (phraseMatch) {
    expanded.add(phraseMatch);
    phraseMatch.split(' ').forEach(w => expanded.add(w));
  }

  // 2. Try 3-word combinations
  for (let i = 0; i < tokens.length - 2; i++) {
    const trigram = `${tokens[i]} ${tokens[i + 1]} ${tokens[i + 2]}`;
    const m = INGREDIENT_ALIASES[trigram];
    if (m) { expanded.add(m); m.split(' ').forEach(w => expanded.add(w)); }
  }

  // 3. Try 2-word combinations (bigrams)
  for (let i = 0; i < tokens.length - 1; i++) {
    const bigram = `${tokens[i]} ${tokens[i + 1]}`;
    const m = INGREDIENT_ALIASES[bigram];
    if (m) { expanded.add(m); m.split(' ').forEach(w => expanded.add(w)); }
  }

  // 4. Try individual tokens
  for (const token of tokens) {
    const m = INGREDIENT_ALIASES[token];
    if (m) { expanded.add(m); m.split(' ').forEach(w => expanded.add(w)); }
  }

  return Array.from(expanded);
}

/**
 * Strip Unicode diacritics/accents from a string.
 * "făină" → "faina", "măsline" → "masline", "șofran" → "sofran"
 */
function stripDiacritics(str: string): string {
  return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    // Romanian cedilla variants not caught by NFD decomposition
    .replace(/ț/g, 't').replace(/Ț/g, 'T')
    .replace(/ș/g, 's').replace(/Ș/g, 'S')
}

/**
 * Resolve a single ingredient name to its English canonical.
 * Falls back to the original if no alias found.
 * Used when normalising shopping list ingredients from foreign-language recipes.
 *
 * Strips diacritics before lookup so "ulei de măsline" matches "ulei de masline".
 */
export function resolveIngredientName(name: string): string {
  const lower = name.toLowerCase().trim()
  // Try exact match first
  const exact = INGREDIENT_ALIASES[lower]
  if (exact) return exact
  // Try with diacritics stripped (recipes use ă/â/î/ș/ț, dictionary uses ASCII)
  const stripped = stripDiacritics(lower)
  return INGREDIENT_ALIASES[stripped] ?? name
}
