/**
 * Mock data for development when Supabase is not available
 * Used as fallback in API endpoints
 */

export type NutritionInfo = {
  calories: number
  protein: number
  carbs: number
  fat: number
}

export const MOCK_RECIPES = [
  {
     id: 'mock-1',
     slug: 'classic-margherita-pizza',
     title: 'Classic Margherita Pizza',
     summary: 'Pizza italiană tradițională cu mozzarella proaspătă, busuioc și sos de roșii',
     hero_image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80',
     region: 'western-europe',
     votes: 42,
     comments: 8,
     tag: 'Popular',
     badges: ['Testat', 'Popular'],
    dietTags: ['vegetarian'],
    foodTags: ['italian', 'pizza', 'cheese'],
    is_tested: true,
    quality_score: 4.5,
    created_by: {
      id: 'mock-user-1',
      display_name: 'Chef Mario',
      handle: '@chef_mario',
      tier: 'pro' as const,
      avatar_url: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 4,
    nutrition_per_serving: { calories: 480, protein: 22, carbs: 58, fat: 18 }
  },
  {
     id: 'mock-2',
     slug: 'pad-thai-noodles',
     title: 'Authentic Pad Thai',
     summary: 'Clasic al mâncării de stradă tailandeze cu tăiței de orez, crevete și sos de tamarind',
     hero_image_url: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=800&q=80',
     region: 'southeast-asia',
     votes: 67,
     comments: 15,
     tag: 'Trending',
     badges: ['În tendințe', 'Popular'],
    dietTags: ['pescatarian'],
    foodTags: ['thai', 'noodles', 'seafood'],
    is_tested: true,
    quality_score: 4.8,
    created_by: {
      id: 'mock-user-2',
      display_name: 'Thai Kitchen',
      handle: '@thai_kitchen',
      tier: 'pro' as const,
      avatar_url: 'https://images.unsplash.com/photo-1595273670150-bd0c3c392e46?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 2,
    nutrition_per_serving: { calories: 520, protein: 32, carbs: 65, fat: 14 }
  },
   {
     id: 'mock-3',
     slug: 'moroccan-tagine',
     title: 'Moroccan Lamb Tagine',
     summary: 'Mâncare nord-africană gătită lent cu mirodenii aromatice și fructe uscate',
     hero_image_url: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
     region: 'north-africa',
     votes: 28,
     comments: 6,
     tag: 'New',
     badges: ['Testat'],
    dietTags: [],
    foodTags: ['moroccan', 'lamb', 'stew', 'spicy'],
    is_tested: true,
    quality_score: 4.3,
    created_by: {
      id: 'mock-user-3',
      display_name: 'Sahara Spice',
      handle: '@sahara_spice',
      tier: 'amateur' as const,
      avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 6,
    nutrition_per_serving: { calories: 620, protein: 45, carbs: 38, fat: 28 }
  },
  {
    id: 'mock-4',
    slug: 'california-sushi-roll',
    title: 'California Roll',
     summary: 'Sushi în stil american cu crab, avocado și castraveți',
     hero_image_url: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?auto=format&fit=crop&w=800&q=80',
     region: 'east-asia',
     votes: 53,
     comments: 12,
     tag: 'Popular',
     badges: ['Popular'],
    dietTags: ['pescatarian'],
    foodTags: ['japanese', 'sushi', 'seafood'],
    is_tested: false,
    quality_score: 4.0,
    created_by: {
      id: 'mock-user-4',
      display_name: 'Sushi Master',
      handle: '@sushi_master',
      tier: 'pro' as const,
      avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 2,
    nutrition_per_serving: { calories: 580, protein: 22, carbs: 72, fat: 24 }
  },
   {
     id: 'mock-5',
     slug: 'vegan-buddha-bowl',
     title: 'Rainbow Buddha Bowl',
     summary: 'Bol colorat pe bază de plante cu quinoa, legume prăjite și sos tahini',
     hero_image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
     region: 'international',
     votes: 89,
     comments: 22,
     tag: 'Trending',
     badges: ['În tendințe', 'Popular', 'Testat'],
    dietTags: ['vegan', 'gluten-free'],
    foodTags: ['healthy', 'bowl', 'vegetables'],
    is_tested: true,
    quality_score: 4.9,
    created_by: {
      id: 'mock-user-5',
      display_name: 'Plant Power',
      handle: '@plant_power',
      tier: 'amateur' as const,
      avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 4,
    nutrition_per_serving: { calories: 540, protein: 42, carbs: 18, fat: 32 }
  },
  {
    id: 'mock-6',
    slug: 'french-croissants',
    title: 'Buttery French Croissants',
     summary: 'Prăjituri crocante și aurii făcute cu aluat laminat și unt premium',
     hero_image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
     region: 'western-europe',
     votes: 71,
     comments: 18,
     tag: 'Trending',
     badges: ['În tendințe', 'Popular'],
     dietTags: ['vegetarian'],
    foodTags: ['french', 'pastry', 'breakfast'],
    is_tested: true,
    quality_score: 4.7,
    created_by: {
      id: 'mock-user-6',
      display_name: 'Parisian Baker',
      handle: '@parisian_baker',
      tier: 'pro' as const,
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 8,
    nutrition_per_serving: { calories: 390, protein: 12, carbs: 48, fat: 18 }
  },
  {
    id: 'mock-7',
    slug: 'mexican-tacos-al-pastor',
    title: 'Tacos al Pastor',
     summary: 'Tacos de porc marinat cu ananas, coriandru și ceapă',
     hero_image_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
     region: 'north-america',
     votes: 95,
     comments: 28,
     tag: 'Trending',
     badges: ['În tendințe', 'Popular', 'Testat'],
    dietTags: [],
    foodTags: ['mexican', 'tacos', 'pork', 'street-food'],
    is_tested: true,
    quality_score: 4.8,
    created_by: {
      id: 'mock-user-7',
      display_name: 'Taqueria Luna',
      handle: '@taqueria_luna',
      tier: 'amateur' as const,
      avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 3,
    nutrition_per_serving: { calories: 400, protein: 18, carbs: 45, fat: 16 }
  },
  {
    id: 'mock-8',
    slug: 'greek-moussaka',
    title: 'Traditional Greek Moussaka',
     summary: 'Casă de vinete în straturi cu carne condimentată și sos béchamel',
     hero_image_url: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
     region: 'western-europe',
     votes: 34,
     comments: 9,
     tag: 'Popular',
     badges: ['Popular', 'Testat'],
    dietTags: [],
    foodTags: ['greek', 'casserole', 'eggplant'],
    is_tested: true,
    quality_score: 4.4,
    created_by: {
      id: 'mock-user-8',
      display_name: 'Athens Kitchen',
      handle: '@athens_kitchen',
      tier: 'user' as const,
      avatar_url: 'https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 4,
    nutrition_per_serving: { calories: 560, protein: 28, carbs: 38, fat: 34 }
  },
  {
    id: 'mock-9',
    slug: 'indian-butter-chicken',
    title: 'Creamy Butter Chicken',
     summary: 'Curry nord-indian bogat cu pui fragil în sos de smântână și roșii',
     hero_image_url: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
     region: 'south-asia',
     votes: 112,
     comments: 35,
     tag: 'Trending',
     badges: ['În tendințe', 'Popular', 'Testat'],
    dietTags: ['gluten-free'],
    foodTags: ['indian', 'curry', 'chicken'],
    is_tested: true,
    quality_score: 4.9,
    created_by: {
      id: 'mock-user-9',
      display_name: 'Spice Route',
      handle: '@spice_route',
      tier: 'pro' as const,
      avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 4,
    nutrition_per_serving: { calories: 480, protein: 22, carbs: 28, fat: 32 }
  },
  {
    id: 'mock-10',
    slug: 'new-york-cheesecake',
    title: 'Classic New York Cheesecake',
     summary: 'Cheesecake dens și cremos cu crustă de biscuiți graham',
     hero_image_url: 'https://images.unsplash.com/photo-1567171466295-4afa63d45416?auto=format&fit=crop&w=800&q=80',
     region: 'north-america',
     votes: 78,
     comments: 21,
     tag: 'Popular',
     badges: ['Popular', 'Testat'],
    dietTags: ['vegetarian'],
    foodTags: ['dessert', 'cheesecake', 'american'],
    is_tested: true,
    quality_score: 4.6,
    created_by: {
      id: 'mock-user-10',
      display_name: 'Sweet Tooth',
      handle: '@sweet_tooth',
      tier: 'amateur' as const,
      avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 8,
    nutrition_per_serving: { calories: 520, protein: 18, carbs: 68, fat: 22 }
  },
  {
    id: 'mock-11',
    slug: 'korean-bibimbap',
    title: 'Korean Bibimbap Bowl',
     summary: 'Bol de orez mixt cu legume, ou și sos gochujang',
     hero_image_url: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?auto=format&fit=crop&w=800&q=80',
     region: 'east-asia',
     votes: 61,
     comments: 14,
     tag: 'Popular',
     badges: ['Popular'],
    dietTags: ['vegetarian'],
    foodTags: ['korean', 'rice', 'bowl', 'spicy'],
    is_tested: false,
    quality_score: 4.2,
    created_by: {
      id: 'mock-user-11',
      display_name: 'Seoul Food',
      handle: '@seoul_food',
      tier: 'user' as const,
      avatar_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 4,
    nutrition_per_serving: { calories: 460, protein: 26, carbs: 52, fat: 14 }
  },
  {
    id: 'mock-12',
    slug: 'spanish-paella',
    title: 'Seafood Paella Valenciana',
     summary: 'Mâncare tradițională spaniolă de orez cu șofran, fructe de mare și legume',
     hero_image_url: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?auto=format&fit=crop&w=800&q=80',
     region: 'western-europe',
     votes: 47,
     comments: 11,
     tag: 'Popular',
     badges: ['Popular', 'Testat'],
    dietTags: ['pescatarian', 'gluten-free'],
    foodTags: ['spanish', 'rice', 'seafood', 'paella'],
    is_tested: true,
    quality_score: 4.5,
    created_by: {
      id: 'mock-user-12',
      display_name: 'Valencia Kitchen',
      handle: '@valencia_kitchen',
      tier: 'amateur' as const,
      avatar_url: 'https://images.unsplash.com/photo-1502378735452-bc7d86632805?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 4,
    nutrition_per_serving: { calories: 480, protein: 34, carbs: 55, fat: 16 }
  },
  {
    id: 'mock-13',
    slug: 'vegetarian-senegalese-mafe',
    title: 'Vegetarian Senegalese Mafé',
     summary: 'Mâncare senegaleza iconică pe bază de arahide cu ciuperci, tofu și fasole fermentată',
     hero_image_url: 'https://eatwithafia.com/wp-content/uploads/2025/03/DSC09821-scaled-1.jpg',
     region: 'west-africa',
     votes: 44,
     comments: 11,
     tag: '',
     badges: ['Testat'],
    dietTags: ['vegan', 'vegetarian'],
    foodTags: ['senegalese', 'stew', 'peanut', 'west-african'],
    is_tested: true,
    quality_score: 4.7,
    created_by: {
      id: 'mock-user-kwame',
      display_name: 'Kwame Mensah',
      handle: '@kwamecooks',
      tier: 'pro' as const,
      avatar_url: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 4,
    nutrition_per_serving: { calories: 380, protein: 16, carbs: 28, fat: 22 }
  },
  {
    id: 'mock-14',
    slug: 'simple-vegetarian-jollof-rice',
    title: 'Simple Vegetarian Jollof Rice',
     summary: 'Orez într-o oală pe bază de roșii picante care celebrează Africa de Vest - vegetarian și gata de sărbătoare',
     hero_image_url: 'https://eatwithafia.com/wp-content/uploads/2022/12/DSC_0019.jpg',
     region: 'west-africa',
     votes: 89,
     comments: 23,
     tag: 'Popular',
     badges: ['Popular', 'Testat'],
    dietTags: ['vegan', 'vegetarian'],
    foodTags: ['ghanaian', 'rice', 'jollof', 'west-african'],
    is_tested: true,
    quality_score: 4.9,
    created_by: {
      id: 'mock-user-kwame',
      display_name: 'Kwame Mensah',
      handle: '@kwamecooks',
      tier: 'pro' as const,
      avatar_url: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 6,
    nutrition_per_serving: { calories: 340, protein: 8, carbs: 68, fat: 6 }
  },
  {
    id: 'mock-15',
    slug: 'ghanaian-red-bean-stew-atidua',
    title: 'Ghanaian Red Bean Stew (Atidua)',
     summary: 'Mâncare tradițională de sărbătoare cu mazăre roșie, ulei de palmă roșu și fasole fermentată',
     hero_image_url: 'https://eatwithafia.com/wp-content/uploads/2022/01/DSC09465.jpg',
     region: 'west-africa',
     votes: 31,
     comments: 7,
     tag: '',
     badges: ['Testat'],
    dietTags: ['vegan', 'vegetarian'],
    foodTags: ['ghanaian', 'beans', 'stew', 'west-african'],
    is_tested: true,
    quality_score: 4.5,
    created_by: {
      id: 'mock-user-kwame',
      display_name: 'Kwame Mensah',
      handle: '@kwamecooks',
      tier: 'pro' as const,
      avatar_url: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 4,
    nutrition_per_serving: { calories: 290, protein: 14, carbs: 42, fat: 8 }
  },
  {
    id: 'mock-16',
    slug: 'mandazi-mahamri-east-african-fried-dough',
    title: 'Mandazi / Mahamri',
     summary: 'Aluat moale și pufos din Africa de Est cu lapte de cocos și cardamom - o mâncare tradițională de mic dejun swahili',
     hero_image_url: 'https://eatwithafia.com/wp-content/uploads/2026/02/DSC01052-scaled.jpg',
     region: 'east-africa',
     votes: 57,
     comments: 14,
     tag: '',
     badges: ['Testat'],
    dietTags: ['vegan', 'vegetarian'],
    foodTags: ['east-african', 'swahili', 'bread', 'breakfast'],
    is_tested: true,
    quality_score: 4.6,
    created_by: {
      id: 'mock-user-kwame',
      display_name: 'Kwame Mensah',
      handle: '@kwamecooks',
      tier: 'pro' as const,
      avatar_url: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 8,
    nutrition_per_serving: { calories: 195, protein: 4, carbs: 32, fat: 6 }
  },
  {
    id: 'mock-17',
    slug: 'spiced-sorghum-millet-porridge',
    title: 'Spiced Grain Porridge (Sorghum & Millet)',
     summary: 'Terci cald și parfumat fără gluten cu cereale africane indigene și mirodenii calde',
     hero_image_url: 'https://eatwithafia.com/wp-content/uploads/2025/03/DSC09643-scaled-3.jpg',
     region: 'west-africa',
     votes: 22,
     comments: 5,
     tag: '',
     badges: ['Testat'],
    dietTags: ['vegan', 'vegetarian', 'gluten-free'],
    foodTags: ['ghanaian', 'porridge', 'breakfast', 'grains'],
    is_tested: true,
    quality_score: 4.4,
    created_by: {
      id: 'mock-user-kwame',
      display_name: 'Kwame Mensah',
      handle: '@kwamecooks',
      tier: 'pro' as const,
      avatar_url: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 2,
    nutrition_per_serving: { calories: 220, protein: 6, carbs: 44, fat: 3 }
  },
  {
    id: 'mock-18',
    slug: 'waakye-ghanaian-rice-and-beans',
    title: 'Waakye',
     summary: 'Mâncare ghaneeză iubită într-o oală cu mazăre cu ochi negri și orez cu tulpini de sorgo pentru o nuanță pământoasă distinctivă',
     hero_image_url: 'https://eatwithafia.com/wp-content/uploads/2021/06/DSC_1283-1.jpg',
     region: 'west-africa',
     votes: 63,
     comments: 17,
     tag: 'Popular',
     badges: ['Popular', 'Testat'],
    dietTags: ['vegan', 'vegetarian'],
    foodTags: ['ghanaian', 'rice', 'beans', 'street-food', 'west-african'],
    is_tested: true,
    quality_score: 4.8,
    created_by: {
      id: 'mock-user-kwame',
      display_name: 'Kwame Mensah',
      handle: '@kwamecooks',
      tier: 'pro' as const,
      avatar_url: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?auto=format&fit=crop&w=200&q=80'
    },
    is_saved: false,
    servings: 6,
    nutrition_per_serving: { calories: 310, protein: 11, carbs: 62, fat: 3 }
  }
];

export const MOCK_TRENDING = [...MOCK_RECIPES].sort((a, b) => b.votes - a.votes).slice(0, 10);

export const MOCK_COMMUNITY_THREADS = [
  {
    id: 'thread-1',
    title: 'Best way to achieve crispy pizza crust at home?',
    author: 'Chef Mario',
    replies: 12,
    views: 234,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString() // 2 hours ago
  },
  {
    id: 'thread-2',
    title: 'Substitutes for fish sauce in Thai cooking',
    author: 'Thai Kitchen',
    replies: 8,
    views: 156,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString() // 5 hours ago
  },
  {
    id: 'thread-3',
    title: 'Vegan alternatives to eggs in baking',
    author: 'Plant Power',
    replies: 24,
    views: 487,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString() // 1 day ago
  },
  {
    id: 'thread-4',
    title: 'How to properly temper chocolate',
    author: 'Sweet Tooth',
    replies: 15,
    views: 312,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() // 3 days ago
  }
];

export const MOCK_APPROACHES = [
  { id: 'western-europe',  name: 'Western Europe',  slug: 'western-europe',  description: 'Bucătăria franceză, italiană, spaniolă, greacă și altele' },
  { id: 'northern-europe', name: 'Northern Europe', slug: 'northern-europe', description: 'Bucătării scandinave și britanice' },
  { id: 'eastern-europe',  name: 'Eastern Europe',  slug: 'eastern-europe',  description: 'Bucătării polonă, rusă, balcanică' },
  { id: 'middle-east',     name: 'Middle East',     slug: 'middle-east',     description: 'Bucătării libaneză, turcă, persană' },
  { id: 'central-asia',    name: 'Central Asia',    slug: 'central-asia',    description: 'Bucătării kazahă, uzbecă și din regiunile înconjurătoare' },
  { id: 'east-asia',       name: 'East Asia',       slug: 'east-asia',       description: 'Bucătării japoneză, chineză, coreeană' },
  { id: 'southeast-asia',  name: 'Southeast Asia',  slug: 'southeast-asia',  description: 'Bucătării tailandeză, vietnameză, filipineză' },
  { id: 'south-asia',      name: 'South Asia',      slug: 'south-asia',      description: 'Bucătării indiană, srillankeză, bangladeșană' },
  { id: 'north-africa',    name: 'North Africa',    slug: 'north-africa',    description: 'Bucătării marocană, egipteană, tunisiană' },
  { id: 'west-africa',     name: 'West Africa',     slug: 'west-africa',     description: 'Bucătării nigeriană, ghaneeză, senegaleza' },
  { id: 'east-africa',     name: 'East Africa',     slug: 'east-africa',     description: 'Bucătării etiopiană, keniană, tanzaniană' },
  { id: 'southern-africa', name: 'Southern Africa', slug: 'southern-africa', description: 'Bucătării sud-africană și din regiunile înconjurătoare' },
  { id: 'north-america',   name: 'North America',   slug: 'north-america',   description: 'Bucătării americană, canadiană, mexicană' },
  { id: 'south-america',   name: 'South America',   slug: 'south-america',   description: 'Bucătării braziliană, argentiniană, peruviană' },
  { id: 'oceania',         name: 'Oceania',         slug: 'oceania',         description: 'Bucătării australiană, neozeelandeză, din Pacific' },
  { id: 'international',   name: 'International',   slug: 'international',   description: 'Rețete fusion și globale' },
];

/* ─────────────────────────────────────────────────────────────────────────
   MOCK COCKTAILS
   category: 'alcoholic' | 'non-alcoholic'
   spirit:   base spirit slug (whisky | gin | rum | tequila | vodka | brandy | liqueur | wine | none)
───────────────────────────────────────────────────────────────────────── */
export interface MockCocktail {
  id: string
  slug: string
  title: string
  summary: string
  hero_image_url: string
  category: 'alcoholic' | 'non-alcoholic'
  spirit: string
  spiritLabel: string
  abv: number | null        // approximate ABV %, null for non-alcoholic
  difficulty: 'easy' | 'medium' | 'hard'
  serves: number
  tags: string[]
  votes: number
  quality_score: number
  is_tested: boolean
  created_by: {
    id: string
    display_name: string
    handle: string
    avatar_url: string | null
  }
}

export const MOCK_COCKTAILS: MockCocktail[] = [
  // ── ALCOHOLIC ─────────────────────────────────────────────────────────
  {
    id: 'cocktail-1',
    slug: 'classic-negroni',
    title: 'Classic Negroni',
     summary: 'Iconul italian amar-dulce - părți egale de gin, Campari și vermut dulce, amestecat peste gheață',
     hero_image_url: 'https://images.unsplash.com/photo-1570598912132-0ba1dc952b7d?w=800&q=80',
     category: 'alcoholic',
     spirit: 'gin',
     spiritLabel: 'Gin',
    abv: 24,
    difficulty: 'easy',
    serves: 1,
    tags: ['classic', 'stirred', 'bitter', 'aperitif'],
    votes: 142,
    quality_score: 4.9,
    is_tested: true,
    created_by: { id: 'bar-1', display_name: 'The Bar Cart', handle: '@thebarcart', avatar_url: null },
  },
  {
    id: 'cocktail-2',
    slug: 'old-fashioned',
    title: 'Old Fashioned',
     summary: 'Whisky, zahăr și amari - cocktailul original, amestecat la perfecțiune mătăsoasă',
     hero_image_url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
     category: 'alcoholic',
     spirit: 'whisky',
     spiritLabel: 'Whisky',
    abv: 32,
    difficulty: 'easy',
    serves: 1,
    tags: ['classic', 'stirred', 'spirit-forward', 'american'],
    votes: 198,
    quality_score: 4.9,
    is_tested: true,
    created_by: { id: 'bar-1', display_name: 'The Bar Cart', handle: '@thebarcart', avatar_url: null },
  },
  {
    id: 'cocktail-3',
    slug: 'mojito',
    title: 'Classic Mojito',
     summary: 'Rom cuban, lămâie proaspătă, mentă și apă carbogazoasă - crocant, răcoritor și perfect pentru o seară lungă',
     hero_image_url: 'https://images.unsplash.com/photo-1609951651556-5334e2706168?w=800&q=80',
     category: 'alcoholic',
     spirit: 'rum',
     spiritLabel: 'Rum',
    abv: 12,
    difficulty: 'easy',
    serves: 1,
    tags: ['refreshing', 'shaken', 'tropical', 'summer'],
    votes: 175,
    quality_score: 4.7,
    is_tested: true,
    created_by: { id: 'bar-2', display_name: 'Tiki Shaker', handle: '@tikishaker', avatar_url: null },
  },
  {
    id: 'cocktail-4',
    slug: 'margarita',
    title: 'Classic Margarita',
     summary: 'Tequila, triple sec și lămâie proaspătă pe o margine sărată - cocktailul de tequila preferat al lumii',
     hero_image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80',
     category: 'alcoholic',
     spirit: 'tequila',
     spiritLabel: 'Tequila',
    abv: 20,
    difficulty: 'easy',
    serves: 1,
    tags: ['classic', 'shaken', 'citrus', 'party'],
    votes: 210,
    quality_score: 4.8,
    is_tested: true,
    created_by: { id: 'bar-2', display_name: 'Tiki Shaker', handle: '@tikishaker', avatar_url: null },
  },
  {
    id: 'cocktail-5',
    slug: 'espresso-martini',
    title: 'Espresso Martini',
     summary: 'Vodcă, espresso proaspăt și lichior de cafea agitat puternic pentru o finisare mătăsoasă cu trei straturi de spumă',
     hero_image_url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
     category: 'alcoholic',
     spirit: 'vodka',
     spiritLabel: 'Vodka',
    abv: 18,
    difficulty: 'medium',
    serves: 1,
    tags: ['trending', 'shaken', 'coffee', 'after-dinner'],
    votes: 267,
    quality_score: 4.8,
    is_tested: true,
    created_by: { id: 'bar-1', display_name: 'The Bar Cart', handle: '@thebarcart', avatar_url: null },
  },
  {
    id: 'cocktail-6',
    slug: 'aperol-spritz',
    title: 'Aperol Spritz',
     summary: 'Aperol, prosecco și o stropitură de apă carbogazoasă - ritualul orei de aur al Italiei într-un pahar',
     hero_image_url: 'https://images.unsplash.com/photo-1560508180-03f285f67ded?w=800&q=80',
     category: 'alcoholic',
     spirit: 'liqueur',
     spiritLabel: 'Lichior',
    abv: 11,
    difficulty: 'easy',
    serves: 1,
    tags: ['aperitif', 'bubbly', 'summer', 'low-abv'],
    votes: 189,
    quality_score: 4.6,
    is_tested: true,
    created_by: { id: 'bar-3', display_name: 'Spritz Club', handle: '@spritzclub', avatar_url: null },
  },
  {
    id: 'cocktail-7',
    slug: 'dark-stormy',
    title: 'Dark & Stormy',
     summary: 'Rom negru peste bere de ghimbir cu o stropitură de lămâie - curajos, picant și profund satisfăcător',
     hero_image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80',
     category: 'alcoholic',
     spirit: 'rum',
     spiritLabel: 'Rum',
    abv: 14,
    difficulty: 'easy',
    serves: 1,
    tags: ['built', 'ginger', 'tropical', 'refreshing'],
    votes: 88,
    quality_score: 4.5,
    is_tested: true,
    created_by: { id: 'bar-2', display_name: 'Tiki Shaker', handle: '@tikishaker', avatar_url: null },
  },
  {
    id: 'cocktail-8',
    slug: 'whisky-sour',
    title: 'Whisky Sour',
     summary: 'Bourbon, suc de lămâie și zahăr - agitat cu albuș de ou pentru un clasic mătăsos și spumos',
     hero_image_url: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=800&q=80',
     category: 'alcoholic',
     spirit: 'whisky',
     spiritLabel: 'Whisky',
    abv: 16,
    difficulty: 'medium',
    serves: 1,
    tags: ['sour', 'shaken', 'classic', 'egg-white'],
    votes: 134,
    quality_score: 4.7,
    is_tested: true,
    created_by: { id: 'bar-1', display_name: 'The Bar Cart', handle: '@thebarcart', avatar_url: null },
  },
  {
    id: 'cocktail-9',
    slug: 'paloma',
    title: 'Paloma',
     summary: 'Cocktailul cel mai iubit al Mexicului - tequila, apă carbogazoasă de grapefruit și o margine sărată',
     hero_image_url: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800&q=80',
     category: 'alcoholic',
     spirit: 'tequila',
     spiritLabel: 'Tequila',
    abv: 13,
    difficulty: 'easy',
    serves: 1,
    tags: ['refreshing', 'citrus', 'built', 'summer'],
    votes: 112,
    quality_score: 4.6,
    is_tested: true,
    created_by: { id: 'bar-3', display_name: 'Spritz Club', handle: '@spritzclub', avatar_url: null },
  },
  {
    id: 'cocktail-10',
    slug: 'gin-tonic',
    title: 'Perfect Gin & Tonic',
     summary: 'Gin premium, tonic de calitate și garnitura potrivită - ingrediente simple, nuanțe infinite',
     hero_image_url: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&q=80',
     category: 'alcoholic',
     spirit: 'gin',
     spiritLabel: 'Gin',
    abv: 10,
    difficulty: 'easy',
    serves: 1,
    tags: ['built', 'refreshing', 'botanical', 'classic'],
    votes: 156,
    quality_score: 4.7,
    is_tested: true,
    created_by: { id: 'bar-1', display_name: 'The Bar Cart', handle: '@thebarcart', avatar_url: null },
  },

  // ── NON-ALCOHOLIC ─────────────────────────────────────────────────────
  {
    id: 'cocktail-11',
    slug: 'virgin-mojito',
    title: 'Virgin Mojito',
     summary: 'Toată prospețimea unui mojito clasic - mentă, lămâie și apă carbogazoasă, zero alcool',
     hero_image_url: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?w=800&q=80',
     category: 'non-alcoholic',
     spirit: 'none',
     spiritLabel: 'Mocktail',
    abv: 0,
    difficulty: 'easy',
    serves: 1,
    tags: ['mocktail', 'refreshing', 'mint', 'citrus'],
    votes: 98,
    quality_score: 4.6,
    is_tested: true,
    created_by: { id: 'bar-3', display_name: 'Spritz Club', handle: '@spritzclub', avatar_url: null },
  },
  {
    id: 'cocktail-12',
    slug: 'watermelon-agua-fresca',
    title: 'Watermelon Agua Fresca',
     summary: 'Pepene verde proaspăt amestecat, lămâie și o atingere de mentă - o mâncare tradițională de vară mexicană',
     hero_image_url: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80',
     category: 'non-alcoholic',
     spirit: 'none',
     spiritLabel: 'Mocktail',
    abv: 0,
    difficulty: 'easy',
    serves: 2,
    tags: ['mocktail', 'fruity', 'summer', 'blended'],
    votes: 74,
    quality_score: 4.5,
    is_tested: true,
    created_by: { id: 'bar-3', display_name: 'Spritz Club', handle: '@spritzclub', avatar_url: null },
  },
  {
    id: 'cocktail-13',
    slug: 'ginger-lemon-shrub',
    title: 'Ginger & Lemon Shrub',
     summary: 'Oțet de băut, ghimbir proaspăt și lămâie - complex, plin de viață și prietenos cu digestia',
     hero_image_url: 'https://images.unsplash.com/photo-1601314002592-b8734bca6604?w=800&q=80',
     category: 'non-alcoholic',
     spirit: 'none',
     spiritLabel: 'Mocktail',
    abv: 0,
    difficulty: 'medium',
    serves: 1,
    tags: ['mocktail', 'ginger', 'shrub', 'wellness'],
    votes: 55,
    quality_score: 4.4,
    is_tested: true,
    created_by: { id: 'bar-4', display_name: 'Zero Proof Bar', handle: '@zeroproofbar', avatar_url: null },
  },
  {
    id: 'cocktail-14',
    slug: 'hibiscus-lemonade',
    title: 'Hibiscus Lemonade',
     summary: 'Ceai acrișor de hibiscus întâlnește limonada proaspătă - roz vibrant și natural fără cofeină',
     hero_image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80',
     category: 'non-alcoholic',
     spirit: 'none',
     spiritLabel: 'Mocktail',
    abv: 0,
    difficulty: 'easy',
    serves: 4,
    tags: ['mocktail', 'floral', 'citrus', 'party'],
    votes: 82,
    quality_score: 4.6,
    is_tested: true,
    created_by: { id: 'bar-4', display_name: 'Zero Proof Bar', handle: '@zeroproofbar', avatar_url: null },
  },
  {
    id: 'cocktail-15',
    slug: 'matcha-tonic',
    title: 'Iced Matcha Tonic',
     summary: 'Matcha de grad ceremonial, apă tonică și yuzu - energie curată într-un pahar',
     hero_image_url: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=800&q=80',
     category: 'non-alcoholic',
     spirit: 'none',
     spiritLabel: 'Mocktail',
    abv: 0,
    difficulty: 'easy',
    serves: 1,
    tags: ['mocktail', 'matcha', 'wellness', 'japanese'],
    votes: 91,
    quality_score: 4.7,
    is_tested: true,
    created_by: { id: 'bar-4', display_name: 'Zero Proof Bar', handle: '@zeroproofbar', avatar_url: null },
  },
];
