/**
 * USDA FoodData Central — Static kcal per 100g lookup table
 *
 * Values sourced from USDA SR Legacy / FoodData Central (2024).
 * All values are approximate kilocalories per 100 grams of raw/typical ingredient.
 * Canonical names match the output of resolveIngredientName() in ingredient-aliases.ts.
 *
 * American standard: based on FDA/USDA Dietary Reference Intakes.
 */

/** kcal per 100 grams (raw weight unless noted) */
export const USDA_KCAL_PER_100G: Record<string, number> = {

  // ── Poultry ──────────────────────────────────────────────────────────────
  'chicken breast':              165,
  'chicken thigh':               209,
  'chicken drumstick':           172,
  'chicken wing':                203,
  'chicken liver':               119,
  'chicken':                     200,
  'turkey breast':               135,
  'turkey':                      189,
  'duck breast':                 201,
  'duck':                        337,
  'duck leg':                    259,
  'goose':                       371,
  'quail':                       192,
  'pheasant':                    144,
  'guinea fowl':                 158,

  // ── Red Meat ─────────────────────────────────────────────────────────────
  'beef':                        250,
  'ground beef':                 254,
  'minced beef':                 254,
  'steak':                       271,
  'ribeye':                      291,
  'sirloin':                     207,
  'brisket':                     274,
  'beef chuck':                  215,
  'beef tenderloin':             219,
  'beef ribs':                   294,
  'oxtail':                      262,
  'veal':                        172,
  'veal chop':                   195,
  'veal shank':                  144,
  'lamb':                        294,
  'lamb chop':                   294,
  'lamb leg':                    258,
  'lamb shoulder':               270,
  'lamb rack':                   294,
  'pork':                        242,
  'pork chop':                   231,
  'pork loin':                   215,
  'pork shoulder':               263,
  'pork tenderloin':             143,
  'pork ribs':                   292,
  'pork belly':                  518,
  'ground pork':                 263,
  'minced pork':                 263,
  'bacon':                       541,
  'pancetta':                    521,
  'prosciutto':                  250,
  'salami':                      425,
  'chorizo':                     455,
  'sausage':                     301,
  'bratwurst':                   333,
  'hot dog':                     290,
  'ham':                         145,
  'venison':                     158,
  'venison loin':                158,
  'bison':                       146,
  'bison ground':                157,
  'rabbit':                      173,
  'rabbit leg':                  173,
  'goat':                        143,
  'game':                        160,
  'wild boar':                   160,
  'elk':                         111,
  'moose':                       102,
  'offal':                       130,
  'liver':                       135,
  'beef liver':                  135,
  'kidney':                      112,
  'heart':                       112,
  'tripe':                        85,
  'bone marrow':                 786,
  'sweetbreads':                 150,

  // ── Seafood ───────────────────────────────────────────────────────────────
  'salmon':                      208,
  'salmon fillet':               208,
  'smoked salmon':               117,
  'tuna':                        144,
  'canned tuna':                 116,
  'tuna steak':                  184,
  'cod':                          82,
  'cod fillet':                   82,
  'halibut':                     111,
  'tilapia':                     128,
  'sea bass':                    124,
  'bass':                        124,
  'trout':                       148,
  'rainbow trout':               148,
  'mackerel':                    205,
  'sardine':                     208,
  'herring':                     203,
  'anchovy':                     131,
  'swordfish':                   172,
  'mahi mahi':                    85,
  'snapper':                     128,
  'flounder':                     86,
  'sole':                         86,
  'catfish':                     122,
  'pike':                         88,
  'perch':                        91,
  'carp':                        127,
  'eel':                         236,
  'shrimp':                       99,
  'prawn':                        99,
  'tiger prawn':                  99,
  'crab':                         87,
  'king crab':                    84,
  'lobster':                      89,
  'scallop':                      88,
  'squid':                        92,
  'calamari':                     92,
  'octopus':                      82,
  'mussels':                      86,
  'clams':                        74,
  'oysters':                      69,
  'cockles':                      53,
  'crayfish':                     82,
  'abalone':                      98,
  'sea urchin':                  120,
  'caviar':                      264,
  'fish roe':                    143,
  'surimi':                       99,
  'imitation crab':               99,

  // ── Eggs & Egg Products ───────────────────────────────────────────────────
  'eggs':                        155,
  'egg':                         155,
  'egg white':                    52,
  'egg yolk':                    322,
  'whole egg':                   155,
  'quail egg':                   158,
  'duck egg':                    185,

  // ── Plant-Based Proteins ──────────────────────────────────────────────────
  'tofu':                         76,
  'firm tofu':                    83,
  'silken tofu':                  55,
  'tempeh':                      193,
  'seitan':                      370,
  'textured soy protein':        331,
  'tvp':                         331,
  'lupini beans':                119,
  'natto':                       211,
  'mung bean':                   347,
  'adzuki bean':                 329,

  // ── Dairy ─────────────────────────────────────────────────────────────────
  'milk':                         61,
  'whole milk':                   61,
  'skim milk':                    34,
  '2% milk':                      50,
  'buttermilk':                   40,
  'evaporated milk':             135,
  'condensed milk':              321,
  'heavy cream':                 340,
  'heavy whipping cream':        340,
  'whipping cream':              298,
  'light cream':                 195,
  'half and half':               130,
  'cream':                       340,
  'sour cream':                  193,
  'creme fraiche':               292,
  'butter':                      717,
  'unsalted butter':             717,
  'ghee':                        900,
  'clarified butter':            900,
  'yogurt':                       59,
  'plain yogurt':                 59,
  'greek yogurt':                 59,
  'low-fat yogurt':               63,
  'kefir':                        60,
  'cheddar':                     402,
  'parmesan':                    431,
  'parmigiano':                  431,
  'pecorino':                    420,
  'mozzarella':                  280,
  'fresh mozzarella':            253,
  'burrata':                     300,
  'feta':                        264,
  'brie':                        334,
  'camembert':                   300,
  'gouda':                       356,
  'edam':                        357,
  'emmental':                    380,
  'gruyere':                     413,
  'swiss cheese':                380,
  'manchego':                    395,
  'asiago':                      406,
  'fontina':                     389,
  'provolone':                   351,
  'colby':                       394,
  'monterey jack':               373,
  'blue cheese':                 353,
  'gorgonzola':                  353,
  'roquefort':                   369,
  'stilton':                     410,
  'bocconcini':                  253,
  'halloumi':                    321,
  'cottage cheese':               98,
  'ricotta':                     174,
  'cream cheese':                342,
  'mascarpone':                  429,
  'labneh':                      190,
  'quark':                        69,
  'cheese':                      350,
  'ice cream':                   207,
  'gelato':                      180,

  // ── Grains & Starches ─────────────────────────────────────────────────────
  'flour':                       364,
  'all-purpose flour':           364,
  'bread flour':                 361,
  'whole wheat flour':           340,
  'cake flour':                  361,
  'self-raising flour':          352,
  'rye flour':                   325,
  'spelt flour':                 338,
  'almond flour':                576,
  'coconut flour':               400,
  'rice flour':                  366,
  'chickpea flour':              387,
  'cornstarch':                  381,
  'arrowroot':                   357,
  'tapioca':                     358,
  'rice':                        365,
  'white rice':                  365,
  'brown rice':                  370,
  'basmati rice':                349,
  'jasmine rice':                349,
  'wild rice':                   357,
  'arborio rice':                350,
  'sushi rice':                  360,
  'pasta':                       371,
  'spaghetti':                   371,
  'penne':                       371,
  'rigatoni':                    371,
  'fusilli':                     371,
  'farfalle':                    371,
  'tagliatelle':                 350,
  'fettuccine':                  371,
  'lasagna sheets':              371,
  'orzo':                        371,
  'gnocchi':                     130,
  'noodles':                     138,
  'rice noodles':                109,
  'egg noodles':                 138,
  'soba noodles':                336,
  'udon noodles':                114,
  'ramen noodles':               436,
  'vermicelli':                  352,
  'glass noodles':               351,
  'bread':                       265,
  'white bread':                 265,
  'whole wheat bread':           247,
  'sourdough':                   289,
  'rye bread':                   259,
  'pita bread':                  275,
  'naan':                        317,
  'flatbread':                   306,
  'baguette':                    270,
  'ciabatta':                    271,
  'brioche':                     370,
  'bagel':                       245,
  'croissant':                   406,
  'muffin':                      377,
  'oats':                        389,
  'oatmeal':                     389,
  'rolled oats':                 389,
  'steel cut oats':              389,
  'granola':                     471,
  'muesli':                      363,
  'quinoa':                      368,
  'barley':                      354,
  'pearl barley':                352,
  'couscous':                    376,
  'cornmeal':                    362,
  'polenta':                     362,
  'grits':                       362,
  'breadcrumbs':                 395,
  'panko':                       395,
  'pizza dough':                 276,
  'tortilla':                    218,
  'corn tortilla':               218,
  'flour tortilla':              306,
  'taco shell':                  463,
  'wonton wrapper':              292,
  'phyllo dough':                300,
  'puff pastry':                 558,
  'shortcrust pastry':           454,
  'buckwheat':                   343,
  'millet':                      378,
  'amaranth':                    371,
  'teff':                        367,
  'farro':                       340,
  'freekeh':                     355,
  'bulgur':                      342,
  'semolina':                    360,
  'wheat germ':                  382,
  'wheat bran':                  216,
  'corn':                         86,
  'popcorn':                     387,
  'pretzels':                    380,
  'crackers':                    430,
  'rice cakes':                  387,

  // ── Legumes ───────────────────────────────────────────────────────────────
  'chickpeas':                   364,
  'garbanzo beans':              364,
  'lentils':                     353,
  'red lentils':                 353,
  'green lentils':               352,
  'black lentils':               353,
  'black beans':                 341,
  'kidney beans':                337,
  'red kidney beans':            337,
  'white beans':                 333,
  'cannellini beans':            333,
  'navy beans':                  337,
  'pinto beans':                 347,
  'great northern beans':        337,
  'lima beans':                  338,
  'fava beans':                  341,
  'broad beans':                 341,
  'soybeans':                    446,
  'black-eyed peas':             336,
  'cowpeas':                     336,
  'split peas':                  341,
  'green split peas':            341,
  'yellow split peas':           348,
  'peas':                         81,
  'green peas':                   81,
  'snow peas':                    42,
  'snap peas':                    42,
  'hummus':                      177,
  'dal':                         353,
  'refried beans':               115,

  // ── Vegetables ────────────────────────────────────────────────────────────
  'onion':                        40,
  'yellow onion':                 40,
  'red onion':                    40,
  'white onion':                  38,
  'shallot':                      72,
  'leek':                         61,
  'spring onion':                 32,
  'scallion':                     32,
  'chive':                        30,
  'garlic':                      149,
  'garlic clove':                149,
  'garlic powder':               331,
  'tomato':                       18,
  'cherry tomato':                18,
  'roma tomato':                  18,
  'beefsteak tomato':             18,
  'sun-dried tomato':            258,
  'tomato passata':               24,
  'tomato puree':                 38,
  'canned tomato':                17,
  'potato':                       77,
  'russet potato':                79,
  'red potato':                   70,
  'yukon gold potato':            69,
  'sweet potato':                 86,
  'yam':                         118,
  'cassava':                     160,
  'taro':                        112,
  'carrot':                       41,
  'celery':                       16,
  'broccoli':                     34,
  'broccolini':                   35,
  'cauliflower':                  25,
  'romanesco':                    25,
  'spinach':                      23,
  'baby spinach':                 23,
  'kale':                         49,
  'chard':                        19,
  'swiss chard':                  19,
  'silverbeet':                   19,
  'collard greens':               32,
  'mustard greens':               27,
  'turnip greens':                29,
  'beet greens':                  22,
  'watercress':                   11,
  'lettuce':                      15,
  'romaine lettuce':              17,
  'iceberg lettuce':              14,
  'arugula':                      25,
  'endive':                       17,
  'radicchio':                    23,
  'cabbage':                      25,
  'red cabbage':                  31,
  'savoy cabbage':                27,
  'napa cabbage':                 12,
  'bok choy':                     13,
  'pak choi':                     13,
  'brussels sprouts':             43,
  'asparagus':                    20,
  'zucchini':                     17,
  'courgette':                    17,
  'yellow squash':                20,
  'spaghetti squash':             31,
  'butternut squash':             45,
  'acorn squash':                 40,
  'pumpkin':                      26,
  'eggplant':                     25,
  'aubergine':                    25,
  'bell pepper':                  31,
  'red bell pepper':              31,
  'green bell pepper':            20,
  'yellow bell pepper':           27,
  'orange bell pepper':           31,
  'red pepper':                   31,
  'green pepper':                 20,
  'poblano':                      20,
  'anaheim pepper':               18,
  'jalapeno':                     29,
  'serrano':                      32,
  'habanero':                     40,
  'cayenne pepper':              318,
  'chili':                        40,
  'chilli':                       40,
  'bird eye chili':               40,
  'cucumber':                     16,
  'english cucumber':             15,
  'pickle':                       11,
  'gherkin':                      11,
  'mushroom':                     22,
  'white mushroom':               22,
  'cremini mushroom':             22,
  'portobello':                   22,
  'shiitake':                     39,
  'oyster mushroom':              33,
  'chanterelle':                  38,
  'porcini':                      31,
  'enoki':                        37,
  'king oyster mushroom':         33,
  'dried mushroom':              284,
  'truffle':                      92,
  'artichoke':                    47,
  'jerusalem artichoke':          73,
  'beet':                         43,
  'beetroot':                     43,
  'radish':                       16,
  'daikon':                       18,
  'turnip':                       28,
  'rutabaga':                     37,
  'parsnip':                      75,
  'celeriac':                     42,
  'kohlrabi':                     27,
  'fennel':                       31,
  'fennel bulb':                  31,
  'celery root':                  42,
  'water chestnut':               97,
  'bamboo shoot':                 27,
  'bean sprout':                  30,
  'bean sprouts':                 30,
  'baby corn':                    26,
  'okra':                         33,
  'green beans':                  31,
  'haricot vert':                 31,
  'wax beans':                    27,
  'lotus root':                   74,
  'jicama':                       38,
  'chayote':                      19,
  'bitter melon':                 17,
  'nopales':                      16,
  'purslane':                     20,
  'dandelion greens':             45,
  'sorrel':                       22,
  'microgreens':                  35,
  'rhubarb':                      21,
  'endive chicory':               17,
  'witloof':                      17,
  'celtuce':                      17,
  'mizuna':                       22,
  'tatsoi':                       20,
  'fiddlehead fern':              34,
  'nettles':                      42,
  'grape leaves':                 93,

  // ── Fruits ────────────────────────────────────────────────────────────────
  'apple':                        52,
  'granny smith apple':           58,
  'fuji apple':                   54,
  'banana':                       89,
  'plantain':                    122,
  'orange':                       47,
  'blood orange':                 50,
  'mandarin':                     53,
  'tangerine':                    53,
  'clementine':                   47,
  'grapefruit':                   42,
  'pomelo':                       38,
  'lemon':                        29,
  'lime':                         30,
  'yuzu':                         53,
  'strawberry':                   32,
  'blueberry':                    57,
  'raspberry':                    52,
  'blackberry':                   43,
  'gooseberry':                   44,
  'cranberry':                    46,
  'currant':                      56,
  'black currant':                63,
  'elderberry':                   73,
  'boysenberry':                  50,
  'mango':                        60,
  'pineapple':                    50,
  'papaya':                       43,
  'guava':                        68,
  'passion fruit':                97,
  'lychee':                       66,
  'dragon fruit':                 60,
  'rambutan':                     82,
  'jackfruit':                    95,
  'durian':                      147,
  'star fruit':                   31,
  'tamarind':                    239,
  'avocado':                     160,
  'grape':                        69,
  'red grape':                    70,
  'green grape':                  67,
  'watermelon':                   30,
  'cantaloupe':                   34,
  'honeydew':                     36,
  'peach':                        39,
  'nectarine':                    44,
  'pear':                         57,
  'plum':                         46,
  'prune':                       240,
  'apricot':                      48,
  'dried apricot':               241,
  'cherry':                       50,
  'sour cherry':                  50,
  'fig':                          74,
  'dried fig':                   249,
  'date':                        282,
  'medjool date':                277,
  'raisin':                      299,
  'sultana':                     299,
  'pomegranate':                  83,
  'kiwi':                         61,
  'persimmon':                    70,
  'quince':                       57,
  'loquat':                       47,
  'breadfruit':                  103,
  'coconut':                     354,
  'coconut milk':                230,
  'coconut cream':               330,
  'coconut water':                19,
  'desiccated coconut':          592,
  'feijoa':                       61,
  'longan':                       60,
  'kumquat':                      71,
  'tamarillo':                    40,
  'ackee':                       151,
  'plantain (green)':            122,

  // ── Nuts & Seeds ─────────────────────────────────────────────────────────
  'almonds':                     579,
  'blanched almonds':            579,
  'sliced almonds':              579,
  'walnuts':                     654,
  'cashews':                     553,
  'peanuts':                     567,
  'roasted peanuts':             585,
  'pistachios':                  562,
  'pine nuts':                   673,
  'hazelnuts':                   628,
  'pecans':                      691,
  'macadamia':                   718,
  'brazil nuts':                 659,
  'chestnuts':                   245,
  'sesame seeds':                573,
  'black sesame seeds':          573,
  'sunflower seeds':             584,
  'pumpkin seeds':               559,
  'chia seeds':                  486,
  'flaxseed':                    534,
  'hemp seeds':                  553,
  'poppy seeds':                 525,
  'nigella seeds':               345,
  'caraway seeds':               333,
  'fennel seeds':                345,
  'tahini':                      595,
  'peanut butter':               588,
  'almond butter':               614,
  'sunflower butter':            617,
  'cashew butter':               587,
  'hazelnut butter':             628,
  'nutella':                     547,

  // ── Oils & Fats ───────────────────────────────────────────────────────────
  'olive oil':                   884,
  'extra virgin olive oil':      884,
  'vegetable oil':               884,
  'sunflower oil':               884,
  'canola oil':                  884,
  'rapeseed oil':                884,
  'coconut oil':                 862,
  'sesame oil':                  884,
  'peanut oil':                  884,
  'avocado oil':                 884,
  'walnut oil':                  884,
  'flaxseed oil':                884,
  'truffle oil':                 884,
  'chili oil':                   884,
  'lard':                        902,
  'duck fat':                    900,
  'beef tallow':                 902,
  'shortening':                  884,
  'margarine':                   717,

  // ── Condiments & Sauces ───────────────────────────────────────────────────
  'soy sauce':                    53,
  'tamari':                       60,
  'fish sauce':                   35,
  'oyster sauce':                 51,
  'hoisin sauce':                220,
  'teriyaki sauce':              101,
  'worcestershire sauce':         78,
  'worcestershire':               78,
  'ketchup':                     112,
  'tomato ketchup':              112,
  'mustard':                      66,
  'dijon mustard':                66,
  'whole grain mustard':          66,
  'mayo':                        680,
  'mayonnaise':                  680,
  'aioli':                       650,
  'vinegar':                      18,
  'white wine vinegar':           18,
  'red wine vinegar':             19,
  'apple cider vinegar':          21,
  'balsamic vinegar':             88,
  'rice vinegar':                 18,
  'malt vinegar':                 24,
  'sherry vinegar':               24,
  'hot sauce':                    11,
  'tabasco':                      12,
  'sriracha':                     93,
  'sambal oelek':                 35,
  'gochujang':                   100,
  'miso':                        199,
  'red miso':                    199,
  'white miso':                  198,
  'tamarind paste':              239,
  'tamarind concentrate':        239,
  'pesto':                       454,
  'basil pesto':                 454,
  'sun-dried tomato pesto':      440,
  'tomato sauce':                 29,
  'marinara sauce':               55,
  'alfredo sauce':               176,
  'bolognese sauce':             120,
  'bechamel':                    128,
  'hollandaise':                 480,
  'stock':                        17,
  'chicken stock':                17,
  'beef stock':                   20,
  'vegetable stock':              12,
  'fish stock':                   10,
  'bone broth':                   20,
  'dashi':                        10,
  'mirin':                       270,
  'rice wine':                    74,
  'shaoxing wine':                74,
  'coconut aminos':               40,
  'liquid aminos':                40,
  'anchovy paste':               131,
  'harissa':                      66,
  'tzatziki':                     54,
  'chimichurri':                 350,
  'tahini sauce':                370,
  'ranch dressing':              140,
  'caesar dressing':             360,
  'italian dressing':            180,
  'balsamic glaze':              250,
  'XO sauce':                    210,

  // ── Sweeteners ────────────────────────────────────────────────────────────
  'sugar':                       387,
  'white sugar':                 387,
  'granulated sugar':            387,
  'brown sugar':                 380,
  'dark brown sugar':            377,
  'caster sugar':                387,
  'icing sugar':                 389,
  'powdered sugar':              389,
  'palm sugar':                  375,
  'jaggery':                     383,
  'coconut sugar':               375,
  'honey':                       304,
  'maple syrup':                 260,
  'agave':                       310,
  'agave nectar':                310,
  'molasses':                    290,
  'treacle':                     290,
  'corn syrup':                  283,
  'golden syrup':                325,
  'simple syrup':                289,
  'stevia':                        0,
  'erythritol':                    0,
  'xylitol':                     240,
  'monk fruit':                    0,
  'date syrup':                  281,
  'pomegranate molasses':        296,

  // ── Fresh Herbs ───────────────────────────────────────────────────────────
  'basil':                        23,
  'fresh basil':                  23,
  'parsley':                      36,
  'flat-leaf parsley':            36,
  'cilantro':                     23,
  'coriander leaves':             23,
  'mint':                         70,
  'spearmint':                    70,
  'peppermint':                   70,
  'dill':                         43,
  'tarragon':                     49,
  'thyme':                       101,
  'fresh thyme':                 101,
  'rosemary':                    131,
  'sage':                        315,
  'oregano':                     265,
  'marjoram':                    271,
  'chervil':                      57,
  'lovage':                       52,
  'lemongrass':                   99,
  'kaffir lime leaves':           99,
  'bay leaf':                    313,
  'savory':                      272,
  'epazote':                      43,
  'shiso':                        37,
  'perilla':                      37,

  // ── Dried Spices & Ground ─────────────────────────────────────────────────
  'black pepper':                251,
  'white pepper':                296,
  'ground pepper':               251,
  'red pepper flakes':           314,
  'cumin':                       375,
  'ground cumin':                375,
  'cumin seeds':                 375,
  'paprika':                     282,
  'smoked paprika':              282,
  'sweet paprika':               282,
  'turmeric':                    312,
  'ground turmeric':             312,
  'cinnamon':                    247,
  'ground cinnamon':             247,
  'cinnamon stick':              247,
  'ginger':                       80,
  'fresh ginger':                 80,
  'ground ginger':               347,
  'ginger paste':                 80,
  'chili powder':                282,
  'cayenne':                     318,
  'allspice':                    263,
  'cardamom':                    311,
  'cardamom pods':               311,
  'cloves':                      274,
  'ground cloves':               274,
  'nutmeg':                      525,
  'ground nutmeg':               525,
  'mace':                        475,
  'star anise':                  337,
  'anise':                       337,
  'coriander seeds':             298,
  'ground coriander':            298,
  'fenugreek':                   323,
  'mustard seeds':               508,
  'mustard powder':              508,
  'saffron':                     310,
  'vanilla':                     288,
  'vanilla extract':             288,
  'vanilla bean':                288,
  'ras el hanout':               290,
  'garam masala':                379,
  'curry powder':                325,
  'five spice':                  298,
  'chinese five spice':          298,
  'za\'atar':                    298,
  'sumac':                       262,
  'baharat':                     300,
  'berbere':                     298,
  'dukkah':                      530,
  'herbes de provence':          259,
  'italian seasoning':           265,
  'old bay':                     245,
  'cajun seasoning':             235,
  'jerk seasoning':              220,
  'onion powder':                341,
  'celery salt':                 219,
  'celery seeds':                392,
  'dill seeds':                  305,
  'dried mint':                  285,
  'dried basil':                 233,
  'dried oregano':               306,
  'dried thyme':                 276,
  'dried rosemary':              331,
  'dried parsley':               292,
  'dried cilantro':              279,
  'dried chili flakes':          314,
  'salt':                          0,
  'sea salt':                      0,
  'kosher salt':                   0,
  'pink himalayan salt':           0,
  'fleur de sel':                  0,

  // ── Baking ────────────────────────────────────────────────────────────────
  'baking powder':                53,
  'baking soda':                   0,
  'cream of tartar':             218,
  'yeast':                       325,
  'active dry yeast':            325,
  'instant yeast':               325,
  'cocoa powder':                228,
  'dutch cocoa':                 228,
  'dark chocolate':              598,
  'dark chocolate chips':        516,
  'milk chocolate':              535,
  'white chocolate':             539,
  'chocolate chips':             516,
  'semisweet chocolate':         479,
  'unsweetened chocolate':       501,
  'cacao nibs':                  500,
  'cacao powder':                228,
  'marzipan':                    472,
  'gelatin':                     335,
  'agar agar':                   306,
  'pectin':                      162,
  'xanthan gum':                 180,

  // ── Alcohol (cooking) ─────────────────────────────────────────────────────
  'wine':                         83,
  'red wine':                     85,
  'white wine':                   82,
  'rose wine':                    83,
  'sparkling wine':               80,
  'champagne':                    80,
  'beer':                         43,
  'dark beer':                    55,
  'lager':                        43,
  'stout':                        60,
  'brandy':                      231,
  'rum':                         231,
  'dark rum':                    231,
  'whiskey':                     250,
  'bourbon':                     250,
  'vodka':                       231,
  'gin':                         263,
  'sake':                         58,
  'sherry':                      116,
  'port':                        157,
  'calvados':                    242,
  'grappa':                      231,
  'liqueur':                     327,

  // ── Preserved & Pickled ───────────────────────────────────────────────────
  'capers':                       23,
  'olives':                      145,
  'green olives':                145,
  'black olives':                115,
  'kalamata olives':             145,
  'cornichons':                   11,
  'sauerkraut':                   19,
  'kimchi':                       15,

  // ── Seaweed & Sea Vegetables ──────────────────────────────────────────────
  'nori':                         35,
  'kombu':                        43,
  'wakame':                       45,
  'dulse':                        33,
  'spirulina':                   290,

  // ── Specialty & Global Ingredients ───────────────────────────────────────
  'paneer':                      265,
  'queso fresco':                285,
  'cotija cheese':               350,
  'nutritional yeast':           325,
  'liquid smoke':                 12,
  'rose water':                    5,
  'orange blossom water':          5,
  'furikake':                    250,
  'bonito flakes':               335,
  'katsuobushi':                 335,
  'dried shrimp':                295,
  'shrimp paste':                 82,
  'fermented black bean':        130,
  'doubanjiang':                  66,
  'black bean paste':            130,
  'gochugaru':                   314,
  'doenjang':                    181,
  'fish cake':                   104,
  'tofu skin':                   158,
  'yuba':                        158,
  'beancurd':                     76,
  'rice paper':                  346,
  'spring roll wrapper':         320,
  'dumpling wrapper':            292,
  'tahdig':                      365,
  'preserved lemon':              26,
  'harissa paste':                66,
  'smen':                        900,
  'mole sauce':                  140,
  'achiote paste':               241,
  'tomatillo':                    32,
  'andouille':                   301,
  'boudin':                      301,
  'plantain chips':              519,
  'yuca chips':                  519,
  'lotus chips':                 390,
}

// ── Unit → grams conversion ────────────────────────────────────────────────────
/** Convert a measured quantity to grams. Returns null if unit is not convertible. */
const UNIT_TO_GRAMS: Record<string, number> = {
  // mass
  'g':            1,
  'gram':         1,
  'grams':        1,
  'kg':           1000,
  'kilogram':     1000,
  'kilograms':    1000,
  'oz':           28.3495,
  'ounce':        28.3495,
  'ounces':       28.3495,
  'lb':           453.592,
  'lbs':          453.592,
  'pound':        453.592,
  'pounds':       453.592,
  // volume → grams (water-equivalent; good approximation for liquids/sauces)
  'ml':           1,
  'milliliter':   1,
  'milliliters':  1,
  'millilitre':   1,
  'l':            1000,
  'liter':        1000,
  'liters':       1000,
  'litre':        1000,
  'litres':       1000,
  'tsp':          5,
  'teaspoon':     5,
  'teaspoons':    5,
  'tbsp':         15,
  'tablespoon':   15,
  'tablespoons':  15,
  'cup':          240,
  'cups':         240,
  'fl oz':        29.5735,
  'fluid oz':     29.5735,
  'pint':         473,
  'pints':        473,
  'quart':        946,
  'quarts':       946,
  // count units — rough gram estimates
  'piece':        100,
  'pieces':       100,
  'slice':         30,
  'slices':        30,
  'bunch':        100,
  'handful':       30,
  'pinch':          1,
  'dash':           1,
  'can':          400,
  'clove':          5,
  'cloves':         5,
  'stalk':         40,
  'sprig':          5,
  'leaf':           2,
  'leaves':         2,
  'sheet':         30,
  'package':      200,
  'pack':         200,
  'bag':          200,
  'jar':          350,
  'bottle':       750,

  // ── Romanian measurement units ────────────────────────────────────────────
  // Volume (tablespoon / teaspoon / cup / glass)
  'lingurita':     5,   // teaspoon (linguriță — without diacritic)
  'lingurite':     5,   // teaspoons plural
  'linguriță':     5,   // teaspoon (with diacritic)
  'lingurițe':     5,   // teaspoons plural (with diacritic)
  'lingura':      15,   // tablespoon (lingură — without diacritic)
  'linguri':      15,   // tablespoons plural
  'lingură':      15,   // tablespoon (with diacritic)
  'cana':        240,   // cup (cană — without diacritic)
  'cani':        240,   // cups plural
  'cană':        240,   // cup (with diacritic)
  'pahar':       200,   // glass / cup (~200 ml)
  'pahare':      200,   // glasses plural
  // Containers
  'cutie':       400,   // can / tin (standard 400 g)
  'cutii':       400,   // cans plural
  'conserva':    400,   // conserved / canned
  'conservă':    400,   // canned (with diacritic)
  'borcan':      350,   // jar
  'borcane':     350,   // jars plural
  'sticla':      750,   // bottle (sticlă)
  'sticlă':      750,   // bottle (with diacritic)
  'punga':       200,   // bag (pungă)
  'pungă':       200,   // bag (with diacritic)
  'pungi':       200,   // bags plural
  'plic':          7,   // sachet / packet (~1 tbsp powder)
  // Count / portion units
  'bucata':      100,   // piece (bucată)
  'bucată':      100,   // piece (with diacritic)
  'bucati':      100,   // pieces (bucăți)
  'bucăți':      100,   // pieces (with diacritic)
  'felie':        30,   // slice
  'felii':        30,   // slices
  'fâșie':        30,   // strip
  'fasie':        30,   // strip (without diacritic)
  'crenguita':     5,   // sprig (crenguță)
  'crenguță':      5,   // sprig (with diacritic)
  'crenguice':     5,   // sprigs variant
  'crenguțe':      5,   // sprigs plural (with diacritic)
  'fir':           5,   // strand / stalk (e.g. fir de pătrunjel)
  'fire':          5,   // strands
  'varf':          1,   // tip (of spoon) — pinch equivalent
  'vârf':          1,   // tip (with diacritic)
  'praf':          1,   // dash / pinch (of powder)
  'capatana':    200,   // head (of garlic/cabbage) — căpățână
  'căpățână':    200,   // head (with diacritics)
  'capatani':    200,   // heads plural
  'legatura':     50,   // bunch/bundle (legătură)
  'legaturi':     50,   // bunches
  'legătură':     50,   // bunch (with diacritic)
}

/**
 * Look up kcal/100g for a canonical ingredient name.
 * Tries exact match first, then partial/substring match on longest key.
 */
export function lookupKcalPer100g(canonicalName: string): number | null {
  const key = canonicalName.toLowerCase().trim()

  if (key in USDA_KCAL_PER_100G) return USDA_KCAL_PER_100G[key]

  // Substring match — find the longest table key contained in the query or vice versa
  let bestMatch: string | null = null
  let bestLen = 0

  for (const tableKey of Object.keys(USDA_KCAL_PER_100G)) {
    if (key.includes(tableKey) || tableKey.includes(key)) {
      if (tableKey.length > bestLen) {
        bestLen = tableKey.length
        bestMatch = tableKey
      }
    }
  }

  return bestMatch ? USDA_KCAL_PER_100G[bestMatch] : null
}

/**
 * Convert a quantity + unit to grams.
 * Returns null when the unit is unknown.
 */
export function toGrams(amount: number, unit: string): number | null {
  const key = unit.toLowerCase().trim()
  const factor = UNIT_TO_GRAMS[key]
  if (factor === undefined) return null
  return amount * factor
}
